// pages/mobile.vue
<template>
  <div class="mobile-home">
    <div class="mobile-home__panel">
      <img :src="logoUrl"  class="mobile-home__logo" />
      <div class="mobile-home__hero">
        <img :src="picUrl" alt="首页视觉" class="mobile-home__hero-img" />
      </div>
      <div class="mobile-home__pc-tip">
        <p class="mobile-home__pc-tip-title">请使用电脑端打开本网页</p>
        <p class="mobile-home__pc-tip-domain">www.aidstudio.com.cn</p>
        <button type="button" class="mobile-home__copy-btn" @click="copyPcUrl">复制电脑端地址</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { message } from 'ant-design-vue'
import logoUrl from '~/assets/img/home/logo-new.svg'
import picUrl from '~/assets/img/icon/pic.svg'

definePageMeta({
  layout: false
})

useHead({
  htmlAttrs: {
    class: 'mobile-only-shell'
  }
})

async function copyPcUrl() {
  const text = 'https://www.aidstudio.com.cn'
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
    } else {
      const input = document.createElement('input')
      input.value = text
      document.body.appendChild(input)
      input.select()
      document.execCommand('copy')
      document.body.removeChild(input)
    }
    message.success('电脑端地址已复制')
  } catch {
    message.error('复制失败，请手动复制地址')
  }
}
</script>

<style scoped>
.mobile-home {
  position: relative;
  min-height: 100vh;
  overflow: hidden;
  background: linear-gradient( 337deg, rgba(14, 89, 250, .2) 0%, rgba(0, 171, 216, .2) 100%);
  color: #fff;
}


.mobile-home__panel {
  position: relative;
  z-index: 1;
  width: min(100%, 420px);
  margin: 0 auto;
  border-radius: 18px;
  padding: 4px 20px 18px;
}

.mobile-home__logo {
  width: 50px;
  height: 50px;
  display: block;
  object-fit: contain;
}

.mobile-home__sub {
  margin: 8px 0 14px;
  font-size: 12px;
  line-height: 1.4;
  color: rgba(230, 237, 243, 0.78);
}

.mobile-home__hero {
  border-radius: 14px;
  overflow: hidden;
}

.mobile-home__hero-img {
  width: 100%;
  height: auto;
  display: block;
}

.mobile-home__content {
  margin-top: 14px;
}

.mobile-home__content h1 {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
  color: #4ae7fd;
}

.mobile-home__content p {
  margin: 8px 0 0;
  font-size: 13px;
  line-height: 1.6;
  color: rgba(230, 237, 243, 0.86);
}

.mobile-home__pc-tip {
  margin-top: 18px;
  padding: 10px 10px 12px;
  border-radius: 14px;
  text-align: center;
}

.mobile-home__pc-tip-title {
  margin: 0;
  font-size: 13px;
  color: #dce7f8;
}

.mobile-home__pc-tip-domain {
  margin: 2px 0 10px;
  font-size: 14px;
  letter-spacing: 0.01em;
  color: #46d8ff;
}

.mobile-home__copy-btn {
  height: 44px;
  border: none;
  border-radius: 999px;
  background: linear-gradient(90deg, #09c7ff 0%, #0a6dff 100%);
  color: #fff;
  font-size: 16px;
  letter-spacing: 0.02em;
  padding: 0 64px;
}

.mobile-home__copy-btn:active {
  transform: translateY(1px);
  filter: brightness(0.95);
}
</style>

// app/mobile/page.tsx
'use client'

import { HtmlShellClass } from '@/components/app/HtmlShellClass'
import { message } from 'antd'
import logoMod from '~/assets/img/home/logo-new.svg'
import picMod from '~/assets/img/icon/pic.svg'
import { assetUrl } from '~/utils/assetUrl'

const logoUrl = assetUrl(logoMod)
const picUrl = assetUrl(picMod)

/** 移动端拦截页：请使用电脑端打开 */
export default function MobilePage() {
  async function copyPcUrl() {
    const text = 'https://www.aidstudio.com.cn'
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(text)
      } else {
        const input = document.createElement('input')
        input.value = text
        document.body.appendChild(input)
        input.select()
        document.execCommand('copy')
        document.body.removeChild(input)
      }
      message.success('电脑端地址已复制')
    } catch {
      message.error('复制失败，请手动复制地址')
    }
  }

  return (
    <div className="mobile-home relative min-h-screen overflow-hidden text-white bg-[linear-gradient(337deg,rgba(14,89,250,0.2)_0%,rgba(0,171,216,0.2)_100%)]">
      <HtmlShellClass classes="mobile-only-shell" />
      <div className="mobile-home__panel relative z-[1] w-[min(100%,420px)] mx-auto rounded-[18px] pt-[4px] px-[20px] pb-[18px]">
        <img src={logoUrl} alt="" className="mobile-home__logo block w-[50px] h-[50px] object-contain" />
        <div className="mobile-home__hero rounded-[14px] overflow-hidden">
          <img src={picUrl} alt="首页视觉" className="mobile-home__hero-img block w-full h-auto" />
        </div>
        <div className="mobile-home__pc-tip mt-[18px] pt-[10px] px-[10px] pb-[12px] rounded-[14px] text-center">
          <p className="m-0 text-[13px] text-[#dce7f8]">请使用电脑端打开本网页</p>
          <p className="mt-[2px] mb-[10px] text-[14px] tracking-[0.01em] text-[#46d8ff]">
            www.aidstudio.com.cn
          </p>
          <button
            type="button"
            className="mobile-home__copy-btn h-[44px] border-none rounded-full bg-[linear-gradient(90deg,#09c7ff_0%,#0a6dff_100%)] text-white text-[16px] tracking-[0.02em] px-[64px] active:translate-y-[1px] active:brightness-95"
            onClick={copyPcUrl}
          >
            复制电脑端地址
          </button>
        </div>
      </div>
    </div>
  )
}
