// components/steps/AgentDropdown.vue
<template>
  <div class="agent-dropdown">
    <!-- 当前选中的智能体（可点击展开） -->
    <div
      class="selected-agent"
      :class="{ expanded: expanded }"
      @click="$emit('toggle')"
    >
      <div class="agent-preview">
        <ShimmerImage
          v-if="value.thumbnail"
          :src="value.thumbnail"
          :alt="value.name"
          img-class="agent-thumbnail__img"
          wrapper-class="agent-thumbnail"
          object-fit="cover"
          reveal-direction="fade"
          :min-shimmer-ms="280"
        />
        <div v-else class="agent-thumbnail placeholder">
          {{ value.name?.slice(0, 1) || '?' }}
        </div>
        <div class="agent-info">
          <div class="agent-name">{{ value.name || '请选择智能体' }}</div>
          <div v-if="expanded && value.desc" class="agent-desc">{{ value.desc }}</div>
        </div>
      </div>
      <UpOutlined v-if="expanded" class="expand-icon" />
      <DownOutlined v-else class="expand-icon" />
    </div>

    <!-- 下拉选项列表 -->
    <Transition name="dropdown">
      <div v-if="expanded" class="options-list">
        <div
          v-for="option in options"
          :key="option.id"
          class="option-item"
          :class="{ selected: value.id === option.id }"
          @click="$emit('select', option)"
        >
          <ShimmerImage
            v-if="option.thumbnail"
            :src="option.thumbnail"
            :alt="option.name"
            img-class="option-thumbnail__img"
            wrapper-class="option-thumbnail"
            object-fit="cover"
            reveal-direction="fade"
            :min-shimmer-ms="280"
          />
          <div v-else class="option-thumbnail placeholder">
            {{ option.name?.slice(0, 1) || '?' }}
          </div>
          <div class="option-info">
            <div class="option-name">{{ option.name }}</div>
            <div v-if="option.desc" class="option-desc">{{ option.desc }}</div>
          </div>
          <CheckCircleFilled v-if="value.id === option.id" class="check-icon" />
        </div>

        <!-- 选择更多模式 -->
        <div class="option-item more-option" @click="$emit('more')">
          <div class="more-icon">
            <MoreOutlined />
          </div>
          <div class="option-info">
            <div class="option-name">选择更多模式</div>
          </div>
          <RightOutlined class="arrow-icon" />
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { DownOutlined, UpOutlined, CheckCircleFilled, MoreOutlined, RightOutlined } from '@ant-design/icons-vue'
import ShimmerImage from '~/components/common/ShimmerImage.vue'
import type { AgentOption } from './AgentPickerModal.vue'

interface Props {
  value: AgentOption
  options: AgentOption[]
  expanded: boolean
}

defineProps<Props>()

defineEmits<{
  toggle: []
  select: [agent: AgentOption]
  more: []
}>()
</script>

<style scoped>
.agent-dropdown {
  position: relative;
  width: 100%;
}

.selected-agent {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem;
  background: var(--create-surface-input, rgba(28, 38, 54, 0.92));
  border: 1px solid var(--gray-200, rgba(96, 124, 158, 0.22));
  border-radius: var(--radius-lg);
  cursor: pointer;
  transition: all 0.2s ease;
}

.selected-agent:hover {
  border-color: var(--accent-400, #4ae7fd);
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.2);
}

.selected-agent.expanded {
  border-color: var(--accent-500, #4ae7fd);
  background: var(--create-surface-panel, rgba(38, 50, 72, 0.94));
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

.agent-preview {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex: 1;
  min-width: 0;
}

.agent-thumbnail {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
  background: rgba(6, 10, 18, 0.55);
  overflow: hidden;
}

.agent-preview :deep(.agent-thumbnail__img) {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.agent-thumbnail.placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--gradient-primary);
  color: white;
  font-weight: 600;
  font-size: 1.125rem;
}

.agent-info {
  flex: 1;
  min-width: 0;
}

.agent-name {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--home-text, #e6edf3);
  margin-bottom: 0.25rem;
}

.agent-desc {
  font-size: 0.8125rem;
  color: var(--home-muted, #8e97a5);
  line-height: 1.5;
}

.expand-icon {
  font-size: 0.875rem;
  color: var(--home-muted, #8e97a5);
  flex-shrink: 0;
  margin-left: 0.5rem;
}

.options-list {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  background: var(--create-surface-modal, rgba(34, 44, 64, 0.98));
  border: 1px solid var(--gray-200, rgba(96, 124, 158, 0.22));
  border-top: none;
  border-radius: 0 0 var(--radius-lg) var(--radius-lg);
  box-shadow: 0 12px 32px rgba(8, 12, 24, 0.45);
  z-index: 100;
  max-height: 400px;
  overflow-y: auto;
  padding-top: 0;
}

.option-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 1rem;
  cursor: pointer;
  transition: all 0.2s ease;
  position: relative;
  border-bottom: 1px solid var(--gray-200);
  border-left: 3px solid transparent;
}

.option-item:last-child {
  border-bottom: none;
}

.option-item:hover {
  background: rgba(74, 231, 253, 0.06);
}

.option-item.selected {
  background: rgba(74, 231, 253, 0.12);
  border-left-color: var(--accent-500, #4ae7fd);
}

.option-item.selected:first-child {
  border-top: none;
}

.option-thumbnail {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
  background: rgba(6, 10, 18, 0.55);
  overflow: hidden;
}

.option-item :deep(.option-thumbnail__img) {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.option-thumbnail.placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.1);
  color: var(--home-text, #e6edf3);
  font-weight: 600;
  font-size: 1.125rem;
}

.option-info {
  flex: 1;
  min-width: 0;
}

.option-name {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--home-text, #e6edf3);
  margin-bottom: 0.25rem;
}

.option-desc {
  font-size: 0.8125rem;
  color: var(--home-muted, #8e97a5);
  line-height: 1.5;
}

.check-icon {
  font-size: 1.125rem;
  color: var(--accent-500, #4ae7fd);
  flex-shrink: 0;
}

.more-option {
  border-top: 1px solid var(--gray-200);
  border-left: 3px solid transparent;
  margin-top: 0.5rem;
  padding-top: 1rem;
}

.more-icon {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  background: rgba(6, 10, 18, 0.55);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  color: var(--home-muted, #8e97a5);
  font-size: 1.25rem;
}

.arrow-icon {
  font-size: 0.875rem;
  color: var(--home-muted, #8e97a5);
  flex-shrink: 0;
}

/* 下拉动画 */
.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.2s ease;
  transform-origin: top;
}

.dropdown-enter-from {
  opacity: 0;
  transform: scaleY(0.95);
}

.dropdown-leave-to {
  opacity: 0;
  transform: scaleY(0.95);
}
</style>

// components/steps/AgentDropdown.tsx
'use client'

import {
CheckCircleFilled,
DownOutlined,
MoreOutlined,
RightOutlined,
UpOutlined
} from '@ant-design/icons'
import { useEffect,useRef,useState } from 'react'
import { ShimmerImage } from '~/components/common/ShimmerImage'
import type { AgentOption } from '~/types/modelAgentOptions'
import './AgentDropdown.css'
/** Compatibility: the legacy AgentPickerModal type now lives in types/modelAgentOptions. */
export type { AgentOption }

interface Props {
  value: AgentOption
  options: AgentOption[]
  expanded: boolean
  onToggle?: () => void
  onSelect?: (agent: AgentOption) => void
  onMore?: () => void
}

/** 原 <Transition name="dropdown"> 时长（transition: all 0.2s ease） */
const DROPDOWN_DURATION_MS = 200

/** 对齐 Vue transition 的 nextFrame：两帧后再切换 class 才能触发过渡 */
function nextFrame(cb: () => void) {
  requestAnimationFrame(() => {
    requestAnimationFrame(cb)
  })
}

export function AgentDropdown({ value, options, expanded, onToggle, onSelect, onMore }: Props) {
  // rendered 控制 DOM 存在（含离场动画期间），transitionClass 复刻 Vue transition 各阶段 class
  const [rendered, setRendered] = useState(false)
  const [transitionClass, setTransitionClass] = useState('')
  const renderedRef = useRef(false)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    if (timerRef.current) {
      clearTimeout(timerRef.current)
      timerRef.current = null
    }

    if (expanded) {
      renderedRef.current = true
      setRendered(true)
      setTransitionClass('dropdown-enter-from dropdown-enter-active')
      nextFrame(() => {
        setTransitionClass('dropdown-enter-active')
        timerRef.current = setTimeout(() => {
          timerRef.current = null
          setTransitionClass('')
        }, DROPDOWN_DURATION_MS)
      })
      return
    }

    if (!renderedRef.current) return
    setTransitionClass('dropdown-leave-active dropdown-leave-to')
    timerRef.current = setTimeout(() => {
      timerRef.current = null
      renderedRef.current = false
      setRendered(false)
      setTransitionClass('')
    }, DROPDOWN_DURATION_MS)
  }, [expanded])

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  return (
    <div className="agent-dropdown">
      {/* 当前选中的智能体（可点击展开） */}
      <div
        className={expanded ? 'selected-agent expanded' : 'selected-agent'}
        onClick={() => onToggle?.()}
      >
        <div className="agent-preview">
          {value.thumbnail ? (
            <ShimmerImage
              src={value.thumbnail}
              alt={value.name}
              imgClass="agent-thumbnail__img"
              wrapperClass="agent-thumbnail"
              objectFit="cover"
              revealDirection="fade"
              minShimmerMs={280}
            />
          ) : (
            <div className="agent-thumbnail placeholder">{value.name?.slice(0, 1) || '?'}</div>
          )}
          <div className="agent-info">
            <div className="agent-name">{value.name || '请选择智能体'}</div>
            {expanded && value.desc ? <div className="agent-desc">{value.desc}</div> : null}
          </div>
        </div>
        {expanded ? <UpOutlined className="expand-icon" /> : <DownOutlined className="expand-icon" />}
      </div>

      {/* 下拉选项列表 */}
      {rendered ? (
        <div className={transitionClass ? `options-list ${transitionClass}` : 'options-list'}>
          {options.map((option) => (
            <div
              key={option.id}
              className={value.id === option.id ? 'option-item selected' : 'option-item'}
              onClick={() => onSelect?.(option)}
            >
              {option.thumbnail ? (
                <ShimmerImage
                  src={option.thumbnail}
                  alt={option.name}
                  imgClass="option-thumbnail__img"
                  wrapperClass="option-thumbnail"
                  objectFit="cover"
                  revealDirection="fade"
                  minShimmerMs={280}
                />
              ) : (
                <div className="option-thumbnail placeholder">
                  {option.name?.slice(0, 1) || '?'}
                </div>
              )}
              <div className="option-info">
                <div className="option-name">{option.name}</div>
                {option.desc ? <div className="option-desc">{option.desc}</div> : null}
              </div>
              {value.id === option.id ? <CheckCircleFilled className="check-icon" /> : null}
            </div>
          ))}

          {/* 选择更多模式 */}
          <div className="option-item more-option" onClick={() => onMore?.()}>
            <div className="more-icon">
              <MoreOutlined />
            </div>
            <div className="option-info">
              <div className="option-name">选择更多模式</div>
            </div>
            <RightOutlined className="arrow-icon" />
          </div>
        </div>
      ) : null}
    </div>
  )
}

export default AgentDropdown
