// components/steps/CaptureVideoFrameModal.vue
<template>
  <a-modal
    v-model:open="modalOpen"
    :width="1050"
    :footer="null"
    :z-index="zIndex"
    :closable="!confirming"
    :mask-closable="!confirming"
    :keyboard="!confirming"
    title="截取视频帧"
    class="capture-video-frame-modal"
    wrap-class-name="create-flow-modal capture-video-frame-modal-wrap"
    @cancel="closeModal"
  >
    <div class="cvfm-content">
      <template v-if="videos.length > 0">
        <section class="cvfm-picker" aria-label="选择分镜原视频">
          <button
            v-if="canScrollLeft"
            type="button"
            class="cvfm-scroll-btn cvfm-scroll-btn--left"
            aria-label="向左查看更多视频"
            @click="scrollVideoStrip(-1)"
          >
            <LeftOutlined />
          </button>
          <div ref="videoStripRef" class="cvfm-video-strip" @scroll="updateScrollState">
            <button
              v-for="video in videos"
              :key="video.id"
              type="button"
              :class="['cvfm-video-card', { 'is-active': selectedVideoId === video.id }]"
              :title="video.label"
              @click="selectVideo(video.id)"
            >
              <ShimmerVideo
                :src="video.url"
                video-class="cvfm-video-card__media"
                wrapper-class="cvfm-video-card__shimmer"
                object-fit="cover"
                preload="metadata"
                reveal-direction="fade"
                :min-shimmer-ms="220"
              />
              <span class="cvfm-video-card__label">{{ video.label }}</span>
            </button>
          </div>
          <button
            v-if="canScrollRight"
            type="button"
            class="cvfm-scroll-btn cvfm-scroll-btn--right"
            aria-label="向右查看更多视频"
            @click="scrollVideoStrip(1)"
          >
            <RightOutlined />
          </button>
        </section>

        <section class="cvfm-preview">
          <video
            v-if="selectedVideo"
            :key="`${selectedVideo.id}-${selectedVideo.url}`"
            ref="videoRef"
            class="cvfm-preview__video"
            :src="selectedVideo.url"
            :poster="selectedVideo.poster"
            playsinline
            preload="auto"
            aria-label="视频预览，点击或按空格播放或暂停"
            @click="togglePlayback"
            @loadedmetadata="onLoadedMetadata"
            @timeupdate="onTimeUpdate"
            @play="onVideoPlay"
            @pause="onVideoPause"
            @ended="onVideoEnded"
            @error="onVideoError"
          />
          <button
            v-if="selectedVideo && videoReady && !videoError && !isPlaying"
            type="button"
            class="dubbing-video-play-btn dubbing-video-play-btn--card"
            aria-label="播放视频"
            @click="togglePlayback"
          />
          <div v-if="videoError" class="cvfm-preview__error">
            <img :src="emptyImageIconUrl" alt="" class="empty-image-icon empty-image-icon--md" >
            <span>视频加载失败，请切换其它视频</span>
          </div>
        </section>

        <section class="cvfm-timeline" aria-label="视频截帧时间轴">
          <div class="cvfm-timeline__main">
            <button
              type="button"
              class="cvfm-play-btn"
              :disabled="!videoReady || videoError"
              :aria-label="isPlaying ? '暂停视频' : '播放视频'"
              @click="togglePlayback"
            >
              <PauseCircleOutlined v-if="isPlaying" />
              <PlayCircleOutlined v-else />
            </button>
            <div
              :class="[
                'cvfm-filmstrip',
                {
                  'is-disabled': !videoReady || videoError,
                  'is-loading': timelineLoading
                }
              ]"
            >
              <span
                v-for="(frame, index) in timelineFrames"
                :key="`${selectedVideoId}-${index}`"
                class="cvfm-filmstrip__frame"
                :style="{ backgroundImage: `url(${frame})` }"
              />
              <span
                v-if="timelineFrames.length === 0"
                class="cvfm-filmstrip__placeholder"
                :class="{ 'is-loading': timelineLoading }"
              />
              <span class="cvfm-filmstrip__playhead" :style="{ left: `${timelineProgress}%` }" />
              <input
                class="cvfm-filmstrip__input"
                type="range"
                min="0"
                :max="duration || 0"
                step="0.001"
                :value="currentTime"
                :disabled="!videoReady || videoError"
                aria-label="选择截帧时间"
                @input="onScrubInput"
              >
            </div>
            <span class="cvfm-time">{{ formatVideoTime(currentTime) }}</span>
          </div>
          <div class="cvfm-timeline__quick">
            <span>快速选取</span>
            <button
              type="button"
              class="cvfm-boundary-btn"
              :disabled="!videoReady || videoError"
              @click="seekToBoundary('start')"
            >
              首帧
            </button>
            <button
              type="button"
              class="cvfm-boundary-btn"
              :disabled="!videoReady || videoError"
              @click="seekToBoundary('end')"
            >
              尾帧
            </button>
          </div>
        </section>
      </template>

      <div v-else class="cvfm-empty">
        <img :src="emptyImageIconUrl" alt="" class="empty-image-icon empty-image-icon--xl" >
        <p>暂无视频</p>
        <span>请先生成当前作品或剧集的分镜视频</span>
      </div>

      <footer class="cvfm-footer">
        <a-button class="cvfm-cancel-btn" :disabled="confirming" @click="closeModal">
          取消
        </a-button>
        <a-button
          type="primary"
          class="cvfm-confirm-btn"
          :loading="confirming"
          :disabled="!selectedVideo || !videoReady || videoError"
          @click="confirmCapture"
        >
          确认截帧
        </a-button>
      </footer>
    </div>
  </a-modal>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import {
  LeftOutlined,
  PauseCircleOutlined,
  PlayCircleOutlined,
  RightOutlined
} from '@ant-design/icons-vue'
import { useCreationStore } from '~/stores/creation'
import {
  collectOriginalStoryboardVideosFromPanels,
  type StoryboardVideoPick
} from '~/utils/collectProjectStoryboardVideos'
import {
  clampVideoFrameTime,
  captureVideoTimelineFrames,
  captureVideoUrlFrame,
  type CapturedVideoFrame
} from '~/utils/videoFrameCapture'
import { formatVideoFrameName } from '~/utils/videoFrameName'
import { uploadImageToOssWithToast } from '~/utils/ossUpload'
import { emptyImageIconUrl } from '~/utils/emptyImageIcon'
import { useVideoPlaybackSpaceShortcut } from '~/composables/useVideoPlaybackSpaceShortcut'
import ShimmerVideo from '~/components/common/ShimmerVideo.vue'

interface Props {
  open: boolean
  projectId: number
  episodeId?: number | null
  zIndex?: number
}
const props = withDefaults(defineProps<Props>(), {
  episodeId: null,
  zIndex: 1200
})

const emit = defineEmits<{
  'update:open': [value: boolean]
  captured: [payload: CapturedVideoFrame]
}>()
const creationStore = useCreationStore()
const modalOpen = computed({
  get: () => props.open,
  set: (value) => emit('update:open', value)
})
const videos = computed<StoryboardVideoPick[]>(() =>
  collectOriginalStoryboardVideosFromPanels(creationStore.formData.storyboardVideo.panels)
)
const selectedVideoId = ref('')
const selectedVideo = computed(
  () => videos.value.find((video) => video.id === selectedVideoId.value) || null
)
const videoRef = ref<HTMLVideoElement | null>(null)
const videoStripRef = ref<HTMLElement | null>(null)
const duration = ref(0)
const currentTime = ref(0)
const videoReady = ref(false)
const videoError = ref(false)
const isPlaying = ref(false)
const confirming = ref(false)
const canScrollLeft = ref(false)
const canScrollRight = ref(false)
const timelineFrames = ref<string[]>([])
const timelineLoading = ref(false)
const timelineProgress = computed(() => {
  if (!duration.value) return 0
  return Math.min(100, Math.max(0, (currentTime.value / duration.value) * 100))
})
const canTogglePlaybackWithSpace = computed(
  () => modalOpen.value && videoReady.value && !videoError.value && !confirming.value
)
useVideoPlaybackSpaceShortcut(canTogglePlaybackWithSpace, togglePlayback)
let resizeObserver: ResizeObserver | null = null
let timelineFrameGeneration = 0
let playbackAnimationFrame: number | null = null

function stopPlaybackProgressAnimation() {
  if (playbackAnimationFrame == null) return
  window.cancelAnimationFrame(playbackAnimationFrame)
  playbackAnimationFrame = null
}

function syncPlaybackProgressFrame() {
  const video = videoRef.value
  if (!video || video.paused || video.ended) {
    playbackAnimationFrame = null
    return
  }
  currentTime.value = Math.max(0, video.currentTime || 0)
  playbackAnimationFrame = window.requestAnimationFrame(syncPlaybackProgressFrame)
}

function startPlaybackProgressAnimation() {
  stopPlaybackProgressAnimation()
  playbackAnimationFrame = window.requestAnimationFrame(syncPlaybackProgressFrame)
}

function syncSelectedVideo() {
  const currentExists = videos.value.some((video) => video.id === selectedVideoId.value)
  if (!currentExists) selectedVideoId.value = videos.value[0]?.id || ''
  void nextTick(updateScrollState)
}
function resetVideoState() {
  stopPlaybackProgressAnimation()
  duration.value = 0
  currentTime.value = 0
  videoReady.value = false
  videoError.value = false
  isPlaying.value = false
  timelineFrameGeneration += 1
  timelineFrames.value = []
  timelineLoading.value = false
}
function selectVideo(id: string) {
  if (selectedVideoId.value === id) return
  videoRef.value?.pause()
  selectedVideoId.value = id
}
function onLoadedMetadata() {
  const video = videoRef.value
  if (!video) return
  duration.value = Number.isFinite(video.duration) ? Math.max(0, video.duration) : 0
  currentTime.value = Math.max(0, video.currentTime || 0)
  videoReady.value = video.videoWidth > 0 && video.videoHeight > 0
  videoError.value = false
  void refreshTimelineFrames()
}
async function refreshTimelineFrames() {
  const sourceUrl = selectedVideo.value?.url || ''
  const generation = ++timelineFrameGeneration
  timelineFrames.value = []
  if (!sourceUrl || !videoReady.value || videoError.value) {
    timelineLoading.value = false
    return
  }

  timelineLoading.value = true
  try {
    const frames = await captureVideoTimelineFrames(sourceUrl, {
      count: 10,
      shouldContinue: () => generation === timelineFrameGeneration && props.open
    })
    if (generation === timelineFrameGeneration) timelineFrames.value = frames
  } catch (error) {
    if (generation === timelineFrameGeneration) {
      timelineFrames.value = []
      console.error('[capture-video-frame] timeline frames failed', error)
    }
  } finally {
    if (generation === timelineFrameGeneration) timelineLoading.value = false
  }
}
function onTimeUpdate() {
  const video = videoRef.value
  if (!video || video.seeking) return
  currentTime.value = Math.max(0, video.currentTime || 0)
}
function onVideoPlay() {
  isPlaying.value = true
  startPlaybackProgressAnimation()
}
function onVideoPause() {
  isPlaying.value = false
  stopPlaybackProgressAnimation()
  onTimeUpdate()
}
function onVideoEnded() {
  isPlaying.value = false
  stopPlaybackProgressAnimation()
  onTimeUpdate()
}
function onVideoError() {
  stopPlaybackProgressAnimation()
  videoReady.value = false
  videoError.value = true
  isPlaying.value = false
}
async function togglePlayback() {
  const video = videoRef.value
  if (!video || !videoReady.value || videoError.value || confirming.value) return
  if (!video.paused) {
    video.pause()
    return
  }
  if (video.ended && duration.value > 0) video.currentTime = 0
  try {
    await video.play()
  } catch {
    message.error('视频播放失败')
  }
}
function setVideoTime(value: number) {
  const video = videoRef.value
  if (!video || !videoReady.value) return
  const safeValue = Math.min(Math.max(0, value), duration.value || 0)
  video.pause()
  isPlaying.value = false
  currentTime.value = safeValue
  video.currentTime = safeValue
}
function onScrubInput(event: Event) {
  setVideoTime(Number((event.target as HTMLInputElement).value))
}

function seekToBoundary(boundary: 'start' | 'end') {
  if (boundary === 'start') {
    setVideoTime(0)
    return
  }
  setVideoTime(clampVideoFrameTime(duration.value, duration.value))
}

async function confirmCapture() {
  const video = videoRef.value
  const source = selectedVideo.value
  if (confirming.value || !video || !source || !videoReady.value || videoError.value) return

  confirming.value = true
  try {
    video.pause()
    const capturedAt = clampVideoFrameTime(currentTime.value, duration.value)
    const capturedAtMs = Math.max(0, Math.floor(capturedAt * 1000))
    const name = formatVideoFrameName(source.label, capturedAtMs, new Date())
    const file = await captureVideoUrlFrame(source.url, capturedAt, name)
    const url = await uploadImageToOssWithToast(file)
    if (!url) return
    emit('captured', {
      url,
      name,
      sourceVideoId: source.id,
      sourceLabel: source.label,
      capturedAtMs
    })
    modalOpen.value = false
  } catch (error) {
    console.error('[capture-video-frame] capture failed', error)
    message.error('截帧失败，请稍后重试')
  } finally {
    confirming.value = false
  }
}

function closeModal() {
  if (confirming.value) return
  modalOpen.value = false
}

function cleanupVideo() {
  const video = videoRef.value
  if (video) {
    video.pause()
    video.removeAttribute('src')
    video.load()
  }
  selectedVideoId.value = ''
  resetVideoState()
}

function updateScrollState() {
  const element = videoStripRef.value
  if (!element) {
    canScrollLeft.value = false
    canScrollRight.value = false
    return
  }
  const maxScrollLeft = Math.max(0, element.scrollWidth - element.clientWidth)
  canScrollLeft.value = element.scrollLeft > 2
  canScrollRight.value = maxScrollLeft - element.scrollLeft > 2
}

function scrollVideoStrip(direction: -1 | 1) {
  const element = videoStripRef.value
  if (!element) return
  element.scrollBy({
    left: direction * Math.max(180, element.clientWidth * 0.8),
    behavior: 'smooth'
  })
}

function formatVideoTime(value: number): string {
  const totalMilliseconds = Math.max(0, Math.floor((Number(value) || 0) * 1000))
  const totalSeconds = Math.floor(totalMilliseconds / 1000)
  const minutes = Math.floor(totalSeconds / 60)
  const seconds = totalSeconds % 60
  const milliseconds = totalMilliseconds % 1000
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(milliseconds).padStart(3, '0')}`
}

watch(
  () => props.open,
  (open) => {
    if (open) {
      syncSelectedVideo()
      return
    }
    cleanupVideo()
  }
)

watch(
  () => [props.projectId, props.episodeId] as const,
  () => {
    if (props.open) {
      cleanupVideo()
      syncSelectedVideo()
    }
  }
)

watch(videos, () => {
  if (props.open) syncSelectedVideo()
})

watch(selectedVideoId, resetVideoState)

onMounted(() => {
  if (typeof ResizeObserver !== 'undefined') {
    resizeObserver = new ResizeObserver(updateScrollState)
    if (videoStripRef.value) resizeObserver.observe(videoStripRef.value)
  }
  window.addEventListener('resize', updateScrollState)
})

watch(videoStripRef, (element, previous) => {
  if (previous) resizeObserver?.unobserve(previous)
  if (element) resizeObserver?.observe(element)
  void nextTick(updateScrollState)
})

onBeforeUnmount(() => {
  cleanupVideo()
  resizeObserver?.disconnect()
  window.removeEventListener('resize', updateScrollState)
})
</script>

<style scoped lang="scss">
.cvfm-content {
  display: flex;
  min-height: 520px;
  flex-direction: column;
  gap: 16px;
  color: var(--home-text, #e6edf3);
}
.cvfm-picker {
  position: relative;
  flex-shrink: 0;
}

.cvfm-video-strip {
  display: flex;
  gap: 10px;
  overflow-x: auto;
  padding: 2px;
  scrollbar-width: none;
  scroll-behavior: smooth;

  &::-webkit-scrollbar {
    display: none;
  }
}

.cvfm-video-card {
  width: 132px;
  min-width: 132px;
  height: 88px;
  padding: 0;
  overflow: hidden;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  background: var(--create-surface-canvas, rgba(17, 22, 33, 0.96));
  color: var(--home-text, #e6edf3);
  cursor: pointer;
  transition:
    border-color 0.2s,
    box-shadow 0.2s;

  &:hover,
  &.is-active {
    border-color: var(--accent-500, #4ae7fd);
  }

  &.is-active {
    box-shadow: 0 0 0 1px rgba(74, 231, 253, 0.25);
  }
}

.cvfm-video-card__shimmer {
  display: block;
  width: 100%;
  height: 62px;
  background: #080b12;
  pointer-events: none;
}

.cvfm-video-card__media {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
  pointer-events: none;
}

.cvfm-video-card__label {
  display: block;
  padding: 4px 7px;
  overflow: hidden;
  font-size: 12px;
  line-height: 18px;
  text-align: left;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cvfm-scroll-btn {
  position: absolute;
  top: 25px;
  z-index: 3;
  display: flex;
  width: 32px;
  height: 32px;
  align-items: center;
  justify-content: center;
  border: 1px solid rgba(74, 231, 253, 0.35);
  border-radius: 50%;
  background: rgba(12, 18, 29, 0.92);
  color: var(--accent-500, #4ae7fd);
  cursor: pointer;
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.38);
}

.cvfm-scroll-btn--left {
  left: 6px;
}
.cvfm-scroll-btn--right {
  right: 6px;
}

.cvfm-preview {
  position: relative;
  display: flex;
  min-height: min(420px, 46vh);
  flex: 1 1 auto;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  border: 1px solid rgba(74, 231, 253, 0.2);
  border-radius: 10px;
  background: #080b12;
}

.cvfm-preview__video {
  display: block;
  width: 100%;
  height: min(52vh, 480px);
  cursor: pointer;
  object-fit: contain;
}
.cvfm-preview__error {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  background: #080b12;
  color: var(--home-muted, #8e97a5);
}

.cvfm-timeline {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.cvfm-timeline__main {
  display: flex;
  align-items: center;
  gap: 10px;
}
.cvfm-timeline__quick {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-left: 44px;
  color: var(--home-muted, #8e97a5);
  font-size: 12px;
}

.cvfm-play-btn,
.cvfm-boundary-btn {
  flex-shrink: 0;
  border: 1px solid rgba(74, 231, 253, 0.3);
  border-radius: 6px;
  background: var(--create-surface-input, rgba(28, 38, 54, 0.92));
  color: var(--home-text, #e6edf3);
  cursor: pointer;

  &:hover:not(:disabled) {
    border-color: var(--accent-500, #4ae7fd);
    color: var(--accent-500, #4ae7fd);
  }

  &:disabled {
    cursor: not-allowed;
    opacity: 0.45;
  }
}

.cvfm-play-btn {
  display: flex;
  width: 34px;
  height: 34px;
  align-items: center;
  justify-content: center;
  padding: 0;
  font-size: 18px;
}

.cvfm-boundary-btn {
  height: 32px;
  padding: 0 12px;
  font-size: 13px;
}

.cvfm-filmstrip {
  position: relative;
  display: flex;
  height: 48px;
  flex: 1 1 auto;
  overflow: hidden;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 6px;
  background: #0a0e15;

  &.is-disabled {
    opacity: 0.5;
  }
}

.cvfm-filmstrip__frame,
.cvfm-filmstrip__placeholder {
  min-width: 0;
  flex: 1 1 0;
  background-position: center;
  background-size: cover;
}

.cvfm-filmstrip__frame + .cvfm-filmstrip__frame {
  border-left: 1px solid rgba(8, 11, 18, 0.7);
}

.cvfm-filmstrip__placeholder {
  background:
    linear-gradient(90deg, rgba(74, 231, 253, 0.08), transparent 45%, rgba(74, 231, 253, 0.08)),
    #0a0e15;
}

.cvfm-filmstrip__placeholder.is-loading,
.cvfm-filmstrip.is-loading .cvfm-filmstrip__placeholder {
  position: relative;
  overflow: hidden;
  background: rgba(14, 18, 28, 0.92);

  &::after {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(
      105deg,
      transparent 35%,
      rgba(74, 231, 253, 0.16) 50%,
      transparent 65%
    );
    transform: translateX(-120%);
    animation: cvfm-filmstrip-shimmer 1.4s ease-in-out infinite;
  }
}

@keyframes cvfm-filmstrip-shimmer {
  0% {
    transform: translateX(-120%);
  }
  100% {
    transform: translateX(120%);
  }
}

.cvfm-filmstrip__playhead {
  position: absolute;
  z-index: 2;
  top: -5px;
  bottom: -5px;
  width: 2px;
  background: #35d66b;
  pointer-events: none;
  transform: translateX(-1px);
  transition: left 80ms linear;
  will-change: left;
  box-shadow: 0 0 6px rgba(53, 214, 107, 0.75);

  &::before {
    position: absolute;
    top: 0;
    left: 50%;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: #35d66b;
    content: '';
    transform: translate(-50%, -50%);
  }
}

.cvfm-filmstrip__input {
  position: absolute;
  z-index: 3;
  inset: 0;
  width: 100%;
  height: 100%;
  margin: 0;
  cursor: pointer;
  opacity: 0;

  &:disabled {
    cursor: not-allowed;
  }
}

.cvfm-time {
  width: 72px;
  flex-shrink: 0;
  color: var(--home-muted, #8e97a5);
  font-variant-numeric: tabular-nums;
  font-size: 12px;
}

.cvfm-empty {
  display: flex;
  min-height: 430px;
  flex: 1 1 auto;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: var(--home-muted, #8e97a5);

  p {
    margin: 14px 0 4px;
    color: var(--home-text, #e6edf3);
    font-size: 16px;
  }

  span {
    font-size: 13px;
  }
}

.cvfm-footer {
  display: flex;
  flex-shrink: 0;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 14px;
  border-top: 1px solid rgba(74, 231, 253, 0.15);
}

.cvfm-cancel-btn,
.cvfm-confirm-btn {
  min-width: 96px;
  height: 36px;
  border-radius: 8px;
}

@media (max-width: 760px) {
  .cvfm-content {
    min-height: 440px;
  }

  .cvfm-preview {
    min-height: 240px;
  }

  .cvfm-time {
    display: none;
  }

  .cvfm-boundary-btn {
    padding: 0 8px;
  }
}
</style>

<style scoped src="~/assets/css/capture-video-frame-modal-responsive.scss" lang="scss"></style>

// components/steps/CaptureVideoFrameModal.tsx
'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import type { ChangeEvent } from 'react'
import { Button, Modal, message } from 'antd'
import {
  LeftOutlined,
  PauseCircleOutlined,
  PlayCircleOutlined,
  RightOutlined
} from '@ant-design/icons'
import { useCreationStore } from '~/stores/creation'
import {
  collectOriginalStoryboardVideosFromPanels,
  type StoryboardVideoPick
} from '~/utils/collectProjectStoryboardVideos'
import {
  clampVideoFrameTime,
  captureVideoTimelineFrames,
  captureVideoUrlFrame,
  type CapturedVideoFrame
} from '~/utils/videoFrameCapture'
import { formatVideoFrameName } from '~/utils/videoFrameName'
import { uploadImageToOssWithToast } from '~/utils/ossUpload'
import { emptyImageIconUrl as emptyImageIconRaw } from '~/utils/emptyImageIcon'
import { assetUrl } from '~/utils/assetUrl'
import { useVideoPlaybackSpaceShortcut } from '~/composables/useVideoPlaybackSpaceShortcut'
import { ShimmerVideo } from '~/components/common/ShimmerVideo'
import './CaptureVideoFrameModal.css'

const emptyImageIconUrl = assetUrl(emptyImageIconRaw)

export interface CaptureVideoFrameModalProps {
  open: boolean
  projectId: number
  episodeId?: number | null
  zIndex?: number
  onOpenChange: (open: boolean) => void
  onCaptured: (payload: CapturedVideoFrame) => void
}

function formatVideoTime(value: number): string {
  const totalMilliseconds = Math.max(0, Math.floor((Number(value) || 0) * 1000))
  const totalSeconds = Math.floor(totalMilliseconds / 1000)
  const minutes = Math.floor(totalSeconds / 60)
  const seconds = totalSeconds % 60
  const milliseconds = totalMilliseconds % 1000
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(milliseconds).padStart(3, '0')}`
}

export function CaptureVideoFrameModal({
  open,
  projectId,
  episodeId = null,
  zIndex = 1200,
  onOpenChange,
  onCaptured
}: CaptureVideoFrameModalProps) {
  const panels = useCreationStore((s) => s.formData.storyboardVideo.panels)
  const videos = useMemo<StoryboardVideoPick[]>(
    () => collectOriginalStoryboardVideosFromPanels(panels),
    [panels]
  )

  const [selectedVideoId, setSelectedVideoId] = useState('')
  const selectedVideo = videos.find((video) => video.id === selectedVideoId) || null

  const videoRef = useRef<HTMLVideoElement | null>(null)
  const videoStripRef = useRef<HTMLElement | null>(null)
  const [duration, setDuration] = useState(0)
  const [currentTime, setCurrentTime] = useState(0)
  const [videoReady, setVideoReadyState] = useState(false)
  const videoReadyRef = useRef(false)
  const [videoError, setVideoErrorState] = useState(false)
  const videoErrorRef = useRef(false)
  const [isPlaying, setIsPlaying] = useState(false)
  const [confirming, setConfirmingState] = useState(false)
  const confirmingRef = useRef(false)
  const [canScrollLeft, setCanScrollLeft] = useState(false)
  const [canScrollRight, setCanScrollRight] = useState(false)
  const [timelineFrames, setTimelineFrames] = useState<string[]>([])
  const [timelineLoading, setTimelineLoading] = useState(false)
  const timelineProgress = !duration
    ? 0
    : Math.min(100, Math.max(0, (currentTime / duration) * 100))
  const canTogglePlaybackWithSpace = open && videoReady && !videoError && !confirming
  useVideoPlaybackSpaceShortcut(canTogglePlaybackWithSpace, togglePlayback)
  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const timelineFrameGenerationRef = useRef(0)
  const playbackAnimationFrameRef = useRef<number | null>(null)
  const openRef = useRef(open)
  openRef.current = open

  function setVideoReady(value: boolean) {
    videoReadyRef.current = value
    setVideoReadyState(value)
  }

  function setVideoError(value: boolean) {
    videoErrorRef.current = value
    setVideoErrorState(value)
  }

  function setConfirming(value: boolean) {
    confirmingRef.current = value
    setConfirmingState(value)
  }

  function stopPlaybackProgressAnimation() {
    if (playbackAnimationFrameRef.current == null) return
    window.cancelAnimationFrame(playbackAnimationFrameRef.current)
    playbackAnimationFrameRef.current = null
  }

  function syncPlaybackProgressFrame() {
    const video = videoRef.current
    if (!video || video.paused || video.ended) {
      playbackAnimationFrameRef.current = null
      return
    }
    setCurrentTime(Math.max(0, video.currentTime || 0))
    playbackAnimationFrameRef.current = window.requestAnimationFrame(syncPlaybackProgressFrame)
  }

  function startPlaybackProgressAnimation() {
    stopPlaybackProgressAnimation()
    playbackAnimationFrameRef.current = window.requestAnimationFrame(syncPlaybackProgressFrame)
  }

  function syncSelectedVideo() {
    const currentExists = videos.some((video) => video.id === selectedVideoId)
    if (!currentExists) setSelectedVideoId(videos[0]?.id || '')
    requestAnimationFrame(updateScrollState)
  }
  function resetVideoState() {
    stopPlaybackProgressAnimation()
    setDuration(0)
    setCurrentTime(0)
    setVideoReady(false)
    setVideoError(false)
    setIsPlaying(false)
    timelineFrameGenerationRef.current += 1
    setTimelineFrames([])
    setTimelineLoading(false)
  }
  function selectVideo(id: string) {
    if (selectedVideoId === id) return
    videoRef.current?.pause()
    setSelectedVideoId(id)
  }
  function onLoadedMetadata() {
    const video = videoRef.current
    if (!video) return
    setDuration(Number.isFinite(video.duration) ? Math.max(0, video.duration) : 0)
    setCurrentTime(Math.max(0, video.currentTime || 0))
    setVideoReady(video.videoWidth > 0 && video.videoHeight > 0)
    setVideoError(false)
    void refreshTimelineFrames()
  }
  async function refreshTimelineFrames() {
    const sourceUrl = selectedVideo?.url || ''
    const generation = ++timelineFrameGenerationRef.current
    setTimelineFrames([])
    if (!sourceUrl || !videoReadyRef.current || videoErrorRef.current) {
      setTimelineLoading(false)
      return
    }

    setTimelineLoading(true)
    try {
      const frames = await captureVideoTimelineFrames(sourceUrl, {
        count: 10,
        shouldContinue: () =>
          generation === timelineFrameGenerationRef.current && openRef.current
      })
      if (generation === timelineFrameGenerationRef.current) setTimelineFrames(frames)
    } catch (error) {
      if (generation === timelineFrameGenerationRef.current) {
        setTimelineFrames([])
        console.error('[capture-video-frame] timeline frames failed', error)
      }
    } finally {
      if (generation === timelineFrameGenerationRef.current) setTimelineLoading(false)
    }
  }
  function onTimeUpdate() {
    const video = videoRef.current
    if (!video || video.seeking) return
    setCurrentTime(Math.max(0, video.currentTime || 0))
  }
  function onVideoPlay() {
    setIsPlaying(true)
    startPlaybackProgressAnimation()
  }
  function onVideoPause() {
    setIsPlaying(false)
    stopPlaybackProgressAnimation()
    onTimeUpdate()
  }
  function onVideoEnded() {
    setIsPlaying(false)
    stopPlaybackProgressAnimation()
    onTimeUpdate()
  }
  function onVideoError() {
    stopPlaybackProgressAnimation()
    setVideoReady(false)
    setVideoError(true)
    setIsPlaying(false)
  }
  async function togglePlayback() {
    const video = videoRef.current
    if (!video || !videoReadyRef.current || videoErrorRef.current || confirmingRef.current) return
    if (!video.paused) {
      video.pause()
      return
    }
    if (video.ended && duration > 0) video.currentTime = 0
    try {
      await video.play()
    } catch {
      message.error('视频播放失败')
    }
  }
  function setVideoTime(value: number) {
    const video = videoRef.current
    if (!video || !videoReadyRef.current) return
    const safeValue = Math.min(Math.max(0, value), duration || 0)
    video.pause()
    setIsPlaying(false)
    setCurrentTime(safeValue)
    video.currentTime = safeValue
  }
  function onScrubInput(event: ChangeEvent<HTMLInputElement>) {
    setVideoTime(Number(event.target.value))
  }

  function seekToBoundary(boundary: 'start' | 'end') {
    if (boundary === 'start') {
      setVideoTime(0)
      return
    }
    setVideoTime(clampVideoFrameTime(duration, duration))
  }

  async function confirmCapture() {
    const video = videoRef.current
    const source = selectedVideo
    if (confirming || !video || !source || !videoReady || videoError) return

    setConfirming(true)
    try {
      video.pause()
      const capturedAt = clampVideoFrameTime(currentTime, duration)
      const capturedAtMs = Math.max(0, Math.floor(capturedAt * 1000))
      const name = formatVideoFrameName(source.label, capturedAtMs, new Date())
      const file = await captureVideoUrlFrame(source.url, capturedAt, name)
      const url = await uploadImageToOssWithToast(file)
      if (!url) return
      onCaptured({
        url,
        name,
        sourceVideoId: source.id,
        sourceLabel: source.label,
        capturedAtMs
      })
      onOpenChange(false)
    } catch (error) {
      console.error('[capture-video-frame] capture failed', error)
      message.error('截帧失败，请稍后重试')
    } finally {
      setConfirming(false)
    }
  }

  function closeModal() {
    if (confirmingRef.current) return
    onOpenChange(false)
  }

  function cleanupVideo() {
    const video = videoRef.current
    if (video) {
      video.pause()
      video.removeAttribute('src')
      video.load()
    }
    setSelectedVideoId('')
    resetVideoState()
  }

  function updateScrollState() {
    const element = videoStripRef.current
    if (!element) {
      setCanScrollLeft(false)
      setCanScrollRight(false)
      return
    }
    const maxScrollLeft = Math.max(0, element.scrollWidth - element.clientWidth)
    setCanScrollLeft(element.scrollLeft > 2)
    setCanScrollRight(maxScrollLeft - element.scrollLeft > 2)
  }

  function scrollVideoStrip(direction: -1 | 1) {
    const element = videoStripRef.current
    if (!element) return
    element.scrollBy({
      left: direction * Math.max(180, element.clientWidth * 0.8),
      behavior: 'smooth'
    })
  }

  /** 原 watch(videoStripRef)：元素变化时切换 ResizeObserver 观察对象并刷新箭头态 */
  function setVideoStripElement(element: HTMLDivElement | null) {
    const previous = videoStripRef.current
    if (previous === element) return
    if (previous) resizeObserverRef.current?.unobserve(previous)
    if (element) resizeObserverRef.current?.observe(element)
    videoStripRef.current = element
    requestAnimationFrame(updateScrollState)
  }

  useEffect(() => {
    if (open) {
      syncSelectedVideo()
      return
    }
    cleanupVideo()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  const scopeMountedRef = useRef(false)
  useEffect(() => {
    // 原 watch([projectId, episodeId]) 非 immediate：跳过首次执行
    if (!scopeMountedRef.current) {
      scopeMountedRef.current = true
      return
    }
    if (openRef.current) {
      cleanupVideo()
      syncSelectedVideo()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, episodeId])

  const videosMountedRef = useRef(false)
  useEffect(() => {
    // 原 watch(videos) 非 immediate：跳过首次执行
    if (!videosMountedRef.current) {
      videosMountedRef.current = true
      return
    }
    if (openRef.current) syncSelectedVideo()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [videos])

  const selectedIdMountedRef = useRef(false)
  useEffect(() => {
    // 原 watch(selectedVideoId) 非 immediate：跳过首次执行
    if (!selectedIdMountedRef.current) {
      selectedIdMountedRef.current = true
      return
    }
    resetVideoState()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedVideoId])

  useEffect(() => {
    if (typeof ResizeObserver !== 'undefined') {
      resizeObserverRef.current = new ResizeObserver(updateScrollState)
      if (videoStripRef.current) resizeObserverRef.current.observe(videoStripRef.current)
    }
    window.addEventListener('resize', updateScrollState)
    return () => {
      cleanupVideo()
      resizeObserverRef.current?.disconnect()
      window.removeEventListener('resize', updateScrollState)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <Modal
      open={open}
      width={1050}
      footer={null}
      zIndex={zIndex}
      closable={!confirming}
      mask={{ closable: !confirming }}
      keyboard={!confirming}
      title="截取视频帧"
      className="capture-video-frame-modal"
      wrapClassName="create-flow-modal capture-video-frame-modal-wrap"
      onCancel={closeModal}
    >
      <div className="cvfm-content">
        {videos.length > 0 ? (
          <>
            <section className="cvfm-picker" aria-label="选择分镜原视频">
              {canScrollLeft && (
                <button
                  type="button"
                  className="cvfm-scroll-btn cvfm-scroll-btn--left"
                  aria-label="向左查看更多视频"
                  onClick={() => scrollVideoStrip(-1)}
                >
                  <LeftOutlined />
                </button>
              )}
              <div ref={setVideoStripElement} className="cvfm-video-strip" onScroll={updateScrollState}>
                {videos.map((video) => (
                  <button
                    key={video.id}
                    type="button"
                    className={`cvfm-video-card${selectedVideoId === video.id ? ' is-active' : ''}`}
                    title={video.label}
                    onClick={() => selectVideo(video.id)}
                  >
                    <ShimmerVideo
                      src={video.url}
                      videoClass="cvfm-video-card__media"
                      wrapperClass="cvfm-video-card__shimmer"
                      objectFit="cover"
                      preload="metadata"
                      revealDirection="fade"
                      minShimmerMs={220}
                    />
                    <span className="cvfm-video-card__label">{video.label}</span>
                  </button>
                ))}
              </div>
              {canScrollRight && (
                <button
                  type="button"
                  className="cvfm-scroll-btn cvfm-scroll-btn--right"
                  aria-label="向右查看更多视频"
                  onClick={() => scrollVideoStrip(1)}
                >
                  <RightOutlined />
                </button>
              )}
            </section>

            <section className="cvfm-preview">
              {selectedVideo && (
                <video
                  key={`${selectedVideo.id}-${selectedVideo.url}`}
                  ref={videoRef}
                  className="cvfm-preview__video"
                  src={selectedVideo.url}
                  poster={selectedVideo.poster}
                  playsInline
                  preload="auto"
                  aria-label="视频预览，点击或按空格播放或暂停"
                  onClick={togglePlayback}
                  onLoadedMetadata={onLoadedMetadata}
                  onTimeUpdate={onTimeUpdate}
                  onPlay={onVideoPlay}
                  onPause={onVideoPause}
                  onEnded={onVideoEnded}
                  onError={onVideoError}
                />
              )}
              {selectedVideo && videoReady && !videoError && !isPlaying && (
                <button
                  type="button"
                  className="dubbing-video-play-btn dubbing-video-play-btn--card"
                  aria-label="播放视频"
                  onClick={togglePlayback}
                />
              )}
              {videoError && (
                <div className="cvfm-preview__error">
                  <img src={emptyImageIconUrl} alt="" className="empty-image-icon empty-image-icon--md" />
                  <span>视频加载失败，请切换其它视频</span>
                </div>
              )}
            </section>

            <section className="cvfm-timeline" aria-label="视频截帧时间轴">
              <div className="cvfm-timeline__main">
                <button
                  type="button"
                  className="cvfm-play-btn"
                  disabled={!videoReady || videoError}
                  aria-label={isPlaying ? '暂停视频' : '播放视频'}
                  onClick={togglePlayback}
                >
                  {isPlaying ? <PauseCircleOutlined /> : <PlayCircleOutlined />}
                </button>
                <div
                  className={`cvfm-filmstrip${!videoReady || videoError ? ' is-disabled' : ''}${timelineLoading ? ' is-loading' : ''}`}
                >
                  {timelineFrames.map((frame, index) => (
                    <span
                      key={`${selectedVideoId}-${index}`}
                      className="cvfm-filmstrip__frame"
                      style={{ backgroundImage: `url(${frame})` }}
                    />
                  ))}
                  {timelineFrames.length === 0 && (
                    <span
                      className={`cvfm-filmstrip__placeholder${timelineLoading ? ' is-loading' : ''}`}
                    />
                  )}
                  <span className="cvfm-filmstrip__playhead" style={{ left: `${timelineProgress}%` }} />
                  <input
                    className="cvfm-filmstrip__input"
                    type="range"
                    min={0}
                    max={duration || 0}
                    step={0.001}
                    value={currentTime}
                    disabled={!videoReady || videoError}
                    aria-label="选择截帧时间"
                    onChange={onScrubInput}
                  />
                </div>
                <span className="cvfm-time">{formatVideoTime(currentTime)}</span>
              </div>
              <div className="cvfm-timeline__quick">
                <span>快速选取</span>
                <button
                  type="button"
                  className="cvfm-boundary-btn"
                  disabled={!videoReady || videoError}
                  onClick={() => seekToBoundary('start')}
                >
                  首帧
                </button>
                <button
                  type="button"
                  className="cvfm-boundary-btn"
                  disabled={!videoReady || videoError}
                  onClick={() => seekToBoundary('end')}
                >
                  尾帧
                </button>
              </div>
            </section>
          </>
        ) : (
          <div className="cvfm-empty">
            <img src={emptyImageIconUrl} alt="" className="empty-image-icon empty-image-icon--xl" />
            <p>暂无视频</p>
            <span>请先生成当前作品或剧集的分镜视频</span>
          </div>
        )}

        <footer className="cvfm-footer">
          <Button className="cvfm-cancel-btn" disabled={confirming} onClick={closeModal}>
            取消
          </Button>
          <Button
            type="primary"
            className="cvfm-confirm-btn"
            loading={confirming}
            disabled={!selectedVideo || !videoReady || videoError}
            onClick={confirmCapture}
          >
            确认截帧
          </Button>
        </footer>
      </div>
    </Modal>
  )
}

export default CaptureVideoFrameModal
