// components/steps/CreateFirstStepFormBody.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { Tooltip } from 'antd'
import GlobalSetting from '~/components/steps/GlobalSetting'
import type { GlobalSettingData } from '~/types'
import { CREATE_FIRST_STEP_DEFAULTS } from '~/utils/createFirstStepDefaults'
import { DICT_ENUM, usePromptDictionary } from '~/composables/usePromptDictionary'
import {
  buildEnumChipOptions,
  normalizeCreationModeValue,
  normalizeModelStrategyValue,
  normalizeScriptTypeValue,
  type GlobalSettingCreationMode,
  type GlobalSettingModelStrategy,
  type GlobalSettingScriptType
} from '~/utils/globalSettingEnums'
import {
  isCreationModeDisabledForScriptType,
  isScriptTypeLockedToPlot,
  PRO_MODE_NO_STORYBOARD_IMAGE_TIP,
  resolveCreationModeForScriptType,
  skipsStoryboardImageGeneration
} from '~/utils/creationModeUiRules'
import ratio16by9IconMod from '~/assets/img/createProcess/16-9.svg'
import ratio9by16IconMod from '~/assets/img/createProcess/9-16.svg'
import ratio4by3IconMod from '~/assets/img/createProcess/4-3.svg'
import ratio3by4IconMod from '~/assets/img/createProcess/3-4.svg'
import ratio1by1IconMod from '~/assets/img/createProcess/1-1.svg'
import ratio21by9IconMod from '~/assets/img/createProcess/21-9.svg'
import ratio21by9IconSelMod from '~/assets/img/createProcess/21-9-sel.svg'
import ratio1by1IconSelMod from '~/assets/img/createProcess/1-1-sel.svg'
import ratio4by3IconSelMod from '~/assets/img/createProcess/4-3-sel.svg'
import ratio3by4IconSelMod from '~/assets/img/createProcess/3-4-sel.svg'
import ratio9by16IconSelMod from '~/assets/img/createProcess/9-16-sel.svg'
import ratio16by9IconSelMod from '~/assets/img/createProcess/16-9-sel.svg'
import unionLeftIconMod from '~/assets/img/createProcess/Union-l.svg'
import unionRightIconMod from '~/assets/img/createProcess/Union-r.svg'
import { SERIES_PROJECT_CONFIG_STORYBOARD_LOCKED_HINT } from '~/utils/seriesProjectConfigGuard'
import { assetUrl } from '~/utils/assetUrl'
import './create-first-step-form-body.css'

const ratio16by9Icon = assetUrl(ratio16by9IconMod)
const ratio9by16Icon = assetUrl(ratio9by16IconMod)
const ratio4by3Icon = assetUrl(ratio4by3IconMod)
const ratio3by4Icon = assetUrl(ratio3by4IconMod)
const ratio1by1Icon = assetUrl(ratio1by1IconMod)
const ratio21by9Icon = assetUrl(ratio21by9IconMod)
const ratio21by9IconSel = assetUrl(ratio21by9IconSelMod)
const ratio1by1IconSel = assetUrl(ratio1by1IconSelMod)
const ratio4by3IconSel = assetUrl(ratio4by3IconSelMod)
const ratio3by4IconSel = assetUrl(ratio3by4IconSelMod)
const ratio9by16IconSel = assetUrl(ratio9by16IconSelMod)
const ratio16by9IconSel = assetUrl(ratio16by9IconSelMod)
const unionLeftIcon = assetUrl(unionLeftIconMod)
const unionRightIcon = assetUrl(unionRightIconMod)

type RatioValue = '16:9' | '9:16' | '4:3' | '3:4' | '1:1' | '21:9'
type ProjectTypeValue = 'movie' | 'series'
type ScriptTypeValue = GlobalSettingScriptType
type StrategyValue = GlobalSettingModelStrategy
type CreationModeValue = GlobalSettingCreationMode

export interface CreateFirstStepFormBodyProps {
  open: boolean
  title: string
  projectType: ProjectTypeValue
  aspectRatio: RatioValue
  scriptType: ScriptTypeValue
  modelStrategy: StrategyValue
  creationMode: CreationModeValue
  modelValue: GlobalSettingData
  flowEditMode?: boolean
  projectTypeLocked?: boolean
  contentConfigLocked?: boolean
  syncProjectTypeFromParent?: boolean
  /** 页面内嵌布局（非弹窗） */
  pageLayout?: boolean
  /** 原 Vue 组件外部 class 透传（弹窗侧 modal-body） */
  className?: string
  onTitleChange: (value: string) => void
  onProjectTypeChange: (value: ProjectTypeValue) => void
  onAspectRatioChange: (value: RatioValue) => void
  onScriptTypeChange: (value: ScriptTypeValue) => void
  onModelStrategyChange: (value: StrategyValue) => void
  onCreationModeChange: (value: CreationModeValue) => void
  onModelValueChange: (value: GlobalSettingData) => void
}

type EnumOption = { value: string; label: string }

const ratioIconByValue: Record<RatioValue, { icon: string; iconSel: string; label: string }> = {
  '16:9': { icon: ratio16by9Icon, iconSel: ratio16by9IconSel, label: '16 : 9' },
  '9:16': { icon: ratio9by16Icon, iconSel: ratio9by16IconSel, label: '9 : 16' },
  '4:3': { icon: ratio4by3Icon, iconSel: ratio4by3IconSel, label: '4 : 3' },
  '3:4': { icon: ratio3by4Icon, iconSel: ratio3by4IconSel, label: '3 : 4' },
  '1:1': { icon: ratio1by1Icon, iconSel: ratio1by1IconSel, label: '1 : 1' },
  '21:9': { icon: ratio21by9Icon, iconSel: ratio21by9IconSel, label: '21 : 9' }
}

function groupOptions(
  groups: { enumType: string; items: { value: string; desc: string }[] }[],
  enumType: string
): EnumOption[] {
  return buildEnumChipOptions(groups, enumType)
}

const PROJECT_TYPE_ORDER: ProjectTypeValue[] = ['series', 'movie']

function sortOptionsByOrder<T extends { value: string }>(
  options: T[],
  order: readonly string[]
): T[] {
  return [...options].sort((a, b) => {
    const ai = order.indexOf(a.value)
    const bi = order.indexOf(b.value)
    return (ai === -1 ? order.length : ai) - (bi === -1 ? order.length : bi)
  })
}

function ensureEnumSelection<T extends string>(
  current: T,
  options: Array<{ value: T }>,
  emitUpdate: (v: T) => void,
  normalize?: (raw: string) => T | null
) {
  if (!options.length) return
  const normalized = normalize ? normalize(String(current)) : null
  if (normalized && options.some((o) => o.value === normalized)) {
    if (normalized !== current) emitUpdate(normalized)
    return
  }
  if (options.some((o) => o.value === current)) return
  emitUpdate(options[0]!.value)
}

/** DOM 更新后再继续（原 await nextTick） */
function nextFrame(): Promise<void> {
  return new Promise((resolve) => requestAnimationFrame(() => resolve()))
}

/** 创建作品第一步表单主体（左侧基本信息 + 右侧风格库），原 CreateFirstStepFormBody.vue */
export function CreateFirstStepFormBody({
  open,
  title,
  projectType,
  aspectRatio,
  scriptType,
  modelStrategy,
  creationMode,
  modelValue,
  flowEditMode = false,
  projectTypeLocked = false,
  contentConfigLocked = false,
  syncProjectTypeFromParent = false,
  pageLayout = false,
  className,
  onTitleChange,
  onProjectTypeChange,
  onAspectRatioChange,
  onScriptTypeChange,
  onModelStrategyChange,
  onCreationModeChange,
  onModelValueChange
}: CreateFirstStepFormBodyProps) {
  // 事件回调 / async 流程读最新 props（等价于 Vue props 响应式引用）
  const propsRef = useRef({ open, projectType, flowEditMode, pageLayout, syncProjectTypeFromParent })
  propsRef.current = { open, projectType, flowEditMode, pageLayout, syncProjectTypeFromParent }
  const emitRef = useRef({
    onTitleChange,
    onProjectTypeChange,
    onAspectRatioChange,
    onScriptTypeChange,
    onModelStrategyChange,
    onCreationModeChange,
    onModelValueChange
  })
  emitRef.current = {
    onTitleChange,
    onProjectTypeChange,
    onAspectRatioChange,
    onScriptTypeChange,
    onModelStrategyChange,
    onCreationModeChange,
    onModelValueChange
  }

  const [projectTypeOptions, setProjectTypeOptions] = useState<
    Array<{ value: ProjectTypeValue; label: string }>
  >([
    { value: 'series', label: '剧集' },
    { value: 'movie', label: '电影' }
  ])

  const [scriptTypeOptions, setScriptTypeOptions] = useState<
    Array<{ value: ScriptTypeValue; label: string }>
  >([])
  const [creationModeOptions, setCreationModeOptions] = useState<
    Array<{ value: CreationModeValue; label: string }>
  >([])
  const [modelStrategyOptions, setModelStrategyOptions] = useState<
    Array<{ value: StrategyValue; label: string }>
  >([])
  const [enumOptionsLoaded, setEnumOptionsLoaded] = useState(false)

  const [ratioOptions, setRatioOptions] = useState<
    Array<{ label: string; value: RatioValue; icon: string; iconSel: string }>
  >(() =>
    Object.entries(ratioIconByValue).map(([value, meta]) => ({
      value: value as RatioValue,
      label: meta.label,
      icon: meta.icon,
      iconSel: meta.iconSel
    }))
  )

  const isNewProjectModal = !flowEditMode
  const isNewProjectModalRef = useRef(isNewProjectModal)
  isNewProjectModalRef.current = isNewProjectModal
  const [leftPanelReady, setLeftPanelReady] = useState(false)

  const contentReady = open && (flowEditMode || pageLayout || leftPanelReady)

  const [leftPanelDraft, setLeftPanelDraftState] = useState({
    projectType: CREATE_FIRST_STEP_DEFAULTS.projectType as ProjectTypeValue,
    scriptType: CREATE_FIRST_STEP_DEFAULTS.scriptType as ScriptTypeValue,
    modelStrategy: CREATE_FIRST_STEP_DEFAULTS.modelStrategy as StrategyValue,
    creationMode: CREATE_FIRST_STEP_DEFAULTS.creationMode as CreationModeValue
  })
  const leftPanelDraftRef = useRef(leftPanelDraft)

  function patchLeftPanelDraft(patch: Partial<typeof leftPanelDraft>) {
    const next = { ...leftPanelDraftRef.current, ...patch }
    leftPanelDraftRef.current = next
    setLeftPanelDraftState(next)
  }

  const displayProjectType = isNewProjectModal ? leftPanelDraft.projectType : projectType
  const displayScriptType = isNewProjectModal ? leftPanelDraft.scriptType : scriptType
  const displayModelStrategy = isNewProjectModal ? leftPanelDraft.modelStrategy : modelStrategy
  const displayCreationMode = isNewProjectModal ? leftPanelDraft.creationMode : creationMode

  const { ensureLoaded: ensureDictLoaded, loaded: dictLoaded, enumList } = usePromptDictionary()

  function resetLeftPanelDraft() {
    const d = CREATE_FIRST_STEP_DEFAULTS
    patchLeftPanelDraft({
      projectType: d.projectType,
      scriptType: d.scriptType,
      modelStrategy: d.modelStrategy,
      creationMode: d.creationMode
    })
  }

  function applyParentProjectType() {
    if (!propsRef.current.syncProjectTypeFromParent) return
    const pt = propsRef.current.projectType
    if (pt === 'series' || pt === 'movie') {
      patchLeftPanelDraft({ projectType: pt })
    }
  }

  function syncLeftPanelToParent() {
    emitRef.current.onProjectTypeChange(leftPanelDraftRef.current.projectType)
    emitRef.current.onScriptTypeChange(leftPanelDraftRef.current.scriptType)
    emitRef.current.onModelStrategyChange(leftPanelDraftRef.current.modelStrategy)
    emitRef.current.onCreationModeChange(leftPanelDraftRef.current.creationMode)
  }

  function initNewProjectLeftPanel() {
    resetLeftPanelDraft()
    applyParentProjectType()
    syncLeftPanelToParent()
  }
  const initNewProjectLeftPanelRef = useRef(initNewProjectLeftPanel)
  initNewProjectLeftPanelRef.current = initNewProjectLeftPanel

  /** 复用风格库同一套字典缓存，与 GlobalSetting.ensureLoaded 合并为一次 enum/list */
  // 原 loadCreateModalEnums：onMounted 触发 ensureLoaded，字典就绪后组装枚举选项（React 侧拆为两个 effect）
  useEffect(() => {
    void ensureDictLoaded()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const enumsInitDoneRef = useRef(false)
  useEffect(() => {
    if (!dictLoaded) return
    const groups = enumList

    const projectTypes = groupOptions(groups, DICT_ENUM.ProjectTypeEnum)
      .map((o) => {
        if (o.value === 'series') return { value: 'series' as const, label: '剧集' }
        if (o.value === 'movie') return { value: 'movie' as const, label: '电影' }
        return null
      })
      .filter(Boolean) as Array<{ value: ProjectTypeValue; label: string }>
    if (projectTypes.length) {
      setProjectTypeOptions(sortOptionsByOrder(projectTypes, PROJECT_TYPE_ORDER))
    }

    const aspectRatios = groupOptions(groups, DICT_ENUM.AspectRatioEnum)
      .map((o) => (o.value in ratioIconByValue ? (o.value as RatioValue) : null))
      .filter(Boolean) as RatioValue[]
    if (aspectRatios.length) {
      setRatioOptions(
        aspectRatios.map((v) => {
          const meta = ratioIconByValue[v]
          return { value: v, label: meta.label, icon: meta.icon, iconSel: meta.iconSel }
        })
      )
    }

    const scripts = groupOptions(groups, DICT_ENUM.ScriptTypeEnum)
      .map((o) => {
        const value = normalizeScriptTypeValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: ScriptTypeValue; label: string }>
    if (scripts.length) setScriptTypeOptions(scripts)

    const creations = groupOptions(groups, DICT_ENUM.CreationModeEnum)
      .map((o) => {
        const value = normalizeCreationModeValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: CreationModeValue; label: string }>
    if (creations.length) setCreationModeOptions(creations)

    const genModes = groupOptions(groups, DICT_ENUM.GenModeEnum)
      .map((o) => {
        const value = normalizeModelStrategyValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: StrategyValue; label: string }>
    if (genModes.length) setModelStrategyOptions(genModes)

    setEnumOptionsLoaded(true)
    // 原 finally 尾部：仅首次组装后按需初始化新建弹窗左栏
    if (!enumsInitDoneRef.current) {
      enumsInitDoneRef.current = true
      if (propsRef.current.open && !propsRef.current.flowEditMode && !propsRef.current.pageLayout) {
        initNewProjectLeftPanelRef.current()
      }
    }
  }, [dictLoaded, enumList])

  function onRightPanelModelUpdate(next: GlobalSettingData) {
    emitRef.current.onModelValueChange({
      selectedStyle: next.selectedStyle,
      myStyles: next.myStyles,
      style: next.style,
      styleSelectionTouched: next.styleSelectionTouched,
      styleLocked: next.styleLocked
    } as GlobalSettingData)
  }

  function pickProjectType(v: ProjectTypeValue) {
    if (isNewProjectModalRef.current) patchLeftPanelDraft({ projectType: v })
    emitRef.current.onProjectTypeChange(v)
  }

  function pickScriptType(v: ScriptTypeValue) {
    if (isNewProjectModalRef.current) patchLeftPanelDraft({ scriptType: v })
    emitRef.current.onScriptTypeChange(v)
    const currentMode = isNewProjectModalRef.current
      ? leftPanelDraftRef.current.creationMode
      : creationMode
    const nextMode = resolveCreationModeForScriptType(currentMode, v)
    if (nextMode !== currentMode) {
      if (isNewProjectModalRef.current) patchLeftPanelDraft({ creationMode: nextMode })
      emitRef.current.onCreationModeChange(nextMode)
    }
  }

  function pickModelStrategy(v: StrategyValue) {
    if (isNewProjectModalRef.current) patchLeftPanelDraft({ modelStrategy: v })
    emitRef.current.onModelStrategyChange(v)
  }

  function pickCreationMode(v: CreationModeValue) {
    if (isCreationModeOptionDisabled(v)) return
    if (isNewProjectModalRef.current) patchLeftPanelDraft({ creationMode: v })
    emitRef.current.onCreationModeChange(v)
    const currentScript = isNewProjectModalRef.current
      ? leftPanelDraftRef.current.scriptType
      : scriptType
    if (isScriptTypeLockedToPlot(v) && currentScript !== 'plot') {
      if (isNewProjectModalRef.current) patchLeftPanelDraft({ scriptType: 'plot' })
      emitRef.current.onScriptTypeChange('plot')
    }
  }

  function isScriptTypeOptionDisabled(value: ScriptTypeValue): boolean {
    return isScriptTypeLockedToPlot(displayCreationMode) && value === 'monologue'
  }

  function isCreationModeOptionDisabled(value: CreationModeValue): boolean {
    return isCreationModeDisabledForScriptType(value, displayScriptType)
  }

  const [hoveredRatio, setHoveredRatio] = useState<RatioValue | null>(null)

  function ratioIconSrc(ratio: { value: RatioValue; icon: string; iconSel: string }) {
    const selected = aspectRatio === ratio.value
    if (contentConfigLocked) return selected ? ratio.iconSel : ratio.icon
    const hover = hoveredRatio === ratio.value
    return selected || hover ? ratio.iconSel : ratio.icon
  }

  // 原 watch([modelStrategy, modelStrategyOptions], immediate)
  useEffect(() => {
    if (flowEditMode && !contentConfigLocked) {
      ensureEnumSelection(
        modelStrategy,
        modelStrategyOptions,
        (v) => emitRef.current.onModelStrategyChange(v),
        normalizeModelStrategyValue
      )
    }
  }, [modelStrategy, modelStrategyOptions, flowEditMode, contentConfigLocked])

  // 原 watch([scriptType, scriptTypeOptions], immediate)
  useEffect(() => {
    if (flowEditMode && !contentConfigLocked) {
      ensureEnumSelection(
        scriptType,
        scriptTypeOptions,
        (v) => emitRef.current.onScriptTypeChange(v),
        normalizeScriptTypeValue
      )
    }
  }, [scriptType, scriptTypeOptions, flowEditMode, contentConfigLocked])

  // 原 watch([creationMode, creationModeOptions, displayScriptType], immediate)
  useEffect(() => {
    if (contentConfigLocked) return
    if (flowEditMode) {
      ensureEnumSelection(
        creationMode,
        creationModeOptions,
        (v) => emitRef.current.onCreationModeChange(v),
        normalizeCreationModeValue
      )
    }
    const resolved = resolveCreationModeForScriptType(creationMode, displayScriptType)
    if (resolved !== creationMode) {
      if (isNewProjectModalRef.current) patchLeftPanelDraft({ creationMode: resolved })
      emitRef.current.onCreationModeChange(resolved)
      return
    }
    if (isScriptTypeLockedToPlot(creationMode) && displayScriptType !== 'plot') {
      if (isNewProjectModalRef.current) patchLeftPanelDraft({ scriptType: 'plot' })
      emitRef.current.onScriptTypeChange('plot')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [creationMode, creationModeOptions, displayScriptType, contentConfigLocked, flowEditMode])

  // 原 watch(open, immediate)：新建弹窗每次打开重置左栏草稿并延迟挂载右侧风格库
  useEffect(() => {
    if (!open) {
      setLeftPanelReady(false)
      return
    }
    if (flowEditMode || pageLayout) {
      setLeftPanelReady(true)
      return
    }
    setLeftPanelReady(false)
    let cancelled = false
    void (async () => {
      await nextFrame()
      if (cancelled) return
      initNewProjectLeftPanelRef.current()
      await nextFrame()
      if (cancelled) return
      setLeftPanelReady(true)
    })()
    return () => {
      cancelled = true
    }
  }, [open, flowEditMode, pageLayout])

  return (
    <div
      className={`create-first-step-form${pageLayout ? ' create-first-step-form--page' : ''}${className ? ` ${className}` : ''}`}
    >
      <div className="left-panel">
        <div className="head_box">
          <img src={unionLeftIcon} alt="" />
          <h4 className="block-title">基本信息</h4>
        </div>
        <div className="content_box">
          {contentConfigLocked && (
            <p className="content-config-lock-hint" role="status">
              {SERIES_PROJECT_CONFIG_STORYBOARD_LOCKED_HINT}
            </p>
          )}
          <div className="field-group inline-options">
            <label className="field-label">作品类型</label>
            <div className="chip-group">
              {projectTypeOptions.map((opt) => (
                <button
                  key={opt.value}
                  type="button"
                  className={`chip${displayProjectType === opt.value ? ' active' : ''}${projectTypeLocked ? ' is-disabled' : ''}`}
                  aria-disabled={projectTypeLocked}
                  onClick={() => !projectTypeLocked && pickProjectType(opt.value)}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          <div className="field-group">
            <label className="field-label">作品名称</label>
            <div className="name-input-wrap">
              <input
                value={title}
                type="text"
                maxLength={25}
                className="name-input"
                placeholder="请输入作品名称"
                onChange={(e) => emitRef.current.onTitleChange(e.target.value)}
              />
              <span className="count-text">{title.length}/25</span>
            </div>
          </div>

          <div className="field-group">
            <label className="field-label">视频比例</label>
            <div className="ratio-grid">
              {ratioOptions.map((ratio) => (
                <button
                  key={ratio.value}
                  type="button"
                  className={`ratio-item${aspectRatio === ratio.value ? ' active' : ''}${contentConfigLocked ? ' is-disabled' : ''}`}
                  disabled={contentConfigLocked}
                  onMouseEnter={() => setHoveredRatio(ratio.value)}
                  onMouseLeave={() => setHoveredRatio(null)}
                  onFocus={() => setHoveredRatio(ratio.value)}
                  onBlur={() => setHoveredRatio(null)}
                  onClick={() => !contentConfigLocked && emitRef.current.onAspectRatioChange(ratio.value)}
                >
                  <img src={ratioIconSrc(ratio)} alt={ratio.label} />
                  <span>{ratio.label}</span>
                </button>
              ))}
            </div>
          </div>

          <div className="field-group inline-options">
            <label className="field-label">剧本类型</label>
            {!enumOptionsLoaded ? (
              <p className="dict-placeholder">加载中…</p>
            ) : !scriptTypeOptions.length ? (
              <p className="dict-placeholder">暂无数据</p>
            ) : (
              <div className="chip-group">
                {scriptTypeOptions.map((opt) =>
                  contentConfigLocked || isScriptTypeOptionDisabled(opt.value) ? (
                    <Tooltip
                      key={opt.value}
                      title={
                        contentConfigLocked
                          ? SERIES_PROJECT_CONFIG_STORYBOARD_LOCKED_HINT
                          : '暂不支持'
                      }
                    >
                      <span className="chip-tooltip-wrap">
                        <button
                          type="button"
                          className={`chip is-disabled${displayScriptType === opt.value ? ' active' : ''}`}
                          disabled
                        >
                          {opt.label}
                        </button>
                      </span>
                    </Tooltip>
                  ) : (
                    <button
                      key={opt.value}
                      type="button"
                      className={`chip${displayScriptType === opt.value ? ' active' : ''}`}
                      onClick={() => pickScriptType(opt.value)}
                    >
                      {opt.label}
                    </button>
                  )
                )}
              </div>
            )}
          </div>

          <div className="field-group inline-options">
            <label className="field-label">模型策略</label>
            {!enumOptionsLoaded ? (
              <p className="dict-placeholder">加载中…</p>
            ) : !modelStrategyOptions.length ? (
              <p className="dict-placeholder">暂无数据</p>
            ) : (
              <div className="chip-group">
                {modelStrategyOptions.map((opt) => (
                  <button
                    key={opt.value}
                    type="button"
                    className={`chip${displayModelStrategy === opt.value ? ' active' : ''}${contentConfigLocked ? ' is-disabled' : ''}`}
                    disabled={contentConfigLocked}
                    onClick={() => !contentConfigLocked && pickModelStrategy(opt.value)}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className="field-group inline-options">
            <label className="field-label">创作模式</label>
            {!enumOptionsLoaded ? (
              <p className="dict-placeholder">加载中…</p>
            ) : !creationModeOptions.length ? (
              <p className="dict-placeholder">暂无数据</p>
            ) : (
              <div className="chip-group">
                {creationModeOptions.map((opt) =>
                  contentConfigLocked || isCreationModeOptionDisabled(opt.value) ? (
                    <Tooltip
                      key={opt.value}
                      title={
                        contentConfigLocked
                          ? SERIES_PROJECT_CONFIG_STORYBOARD_LOCKED_HINT
                          : '解说漫暂不支持该创作模式'
                      }
                    >
                      <span className="chip-tooltip-wrap">
                        <button
                          type="button"
                          className={`chip is-disabled${displayCreationMode === opt.value ? ' active' : ''}`}
                          disabled
                        >
                          {opt.label}
                        </button>
                      </span>
                    </Tooltip>
                  ) : skipsStoryboardImageGeneration(opt.value) ? (
                    <Tooltip key={opt.value} title={PRO_MODE_NO_STORYBOARD_IMAGE_TIP}>
                      <span className="chip-tooltip-wrap">
                        <button
                          type="button"
                          className={`chip${displayCreationMode === opt.value ? ' active' : ''}`}
                          onClick={() => pickCreationMode(opt.value)}
                        >
                          {opt.label}
                        </button>
                      </span>
                    </Tooltip>
                  ) : (
                    <button
                      key={opt.value}
                      type="button"
                      className={`chip${displayCreationMode === opt.value ? ' active' : ''}`}
                      onClick={() => pickCreationMode(opt.value)}
                    >
                      {opt.label}
                    </button>
                  )
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="right-panel">
        <div className="head_box">
          <img src={unionRightIcon} alt="" />
          <h4 className="block-title">我的风格库</h4>
        </div>
        {contentReady && (
          <GlobalSetting
            modelValue={modelValue}
            styleLibraryOnly={true}
            forceStyleLocked={contentConfigLocked}
            styleLockHint="已有剧集生成分镜脚本，画面风格仅可查看。"
            styleThumbSizePx={107}
            description=""
            onModelValueChange={onRightPanelModelUpdate}
          />
        )}
      </div>
    </div>
  )
}

export default CreateFirstStepFormBody

// components/steps/CreateFirstStepFormBody.vue
<template>
  <div class="create-first-step-form" :class="{ 'create-first-step-form--page': pageLayout }">
    <div class="left-panel">
      <div class="head_box">
        <img src="../../assets/img/createProcess/Union-l.svg" alt="" />
        <h4 class="block-title">基本信息</h4>
      </div>
      <div class="content_box">
        <div class="field-group inline-options">
          <label class="field-label">作品类型</label>
          <div class="chip-group">
            <button
              v-for="opt in projectTypeOptions"
              :key="opt.value"
              type="button"
              class="chip"
              :class="{ active: displayProjectType === opt.value, 'is-disabled': projectTypeLocked }"
              :aria-disabled="projectTypeLocked"
              @click="!projectTypeLocked && pickProjectType(opt.value)"
            >
              {{ opt.label }}
            </button>
          </div>
        </div>

        <div class="field-group">
          <label class="field-label">作品名称</label>
          <div class="name-input-wrap">
            <input
              :value="title"
              type="text"
              maxlength="25"
              class="name-input"
              placeholder="请输入作品名称"
              @input="onTitleInput"
            />
            <span class="count-text">{{ title.length }}/25</span>
          </div>
        </div>

        <div class="field-group">
          <label class="field-label">视频比例</label>
          <div class="ratio-grid">
            <button
              v-for="ratio in ratioOptions"
              :key="ratio.value"
              type="button"
              class="ratio-item"
              :class="{ active: aspectRatio === ratio.value }"
              @mouseenter="hoveredRatio = ratio.value"
              @mouseleave="hoveredRatio = null"
              @focus="hoveredRatio = ratio.value"
              @blur="hoveredRatio = null"
              @click="emit('update:aspectRatio', ratio.value)"
            >
              <img :src="ratioIconSrc(ratio)" :alt="ratio.label" />
              <span>{{ ratio.label }}</span>
            </button>
          </div>
        </div>

        <div class="field-group inline-options">
          <label class="field-label">剧本类型</label>
          <p v-if="!enumOptionsLoaded" class="dict-placeholder">加载中…</p>
          <p v-else-if="!scriptTypeOptions.length" class="dict-placeholder">暂无数据</p>
          <div v-else class="chip-group">
            <template v-for="opt in scriptTypeOptions" :key="opt.value">
              <a-tooltip v-if="isScriptTypeOptionDisabled(opt.value)" title="暂不支持">
                <span class="chip-tooltip-wrap">
                  <button
                    type="button"
                    class="chip is-disabled"
                    :class="{ active: displayScriptType === opt.value }"
                    disabled
                  >
                    {{ opt.label }}
                  </button>
                </span>
              </a-tooltip>
              <button
                v-else
                type="button"
                class="chip"
                :class="{ active: displayScriptType === opt.value }"
                @click="pickScriptType(opt.value)"
              >
                {{ opt.label }}
              </button>
            </template>
          </div>
        </div>

        <div class="field-group inline-options">
          <label class="field-label">模型策略</label>
          <p v-if="!enumOptionsLoaded" class="dict-placeholder">加载中…</p>
          <p v-else-if="!modelStrategyOptions.length" class="dict-placeholder">暂无数据</p>
          <div v-else class="chip-group">
            <button
              v-for="opt in modelStrategyOptions"
              :key="opt.value"
              type="button"
              class="chip"
              :class="{ active: displayModelStrategy === opt.value }"
              @click="pickModelStrategy(opt.value)"
            >
              {{ opt.label }}
            </button>
          </div>
        </div>

        <div class="field-group inline-options">
          <label class="field-label">创作模式</label>
          <p v-if="!enumOptionsLoaded" class="dict-placeholder">加载中…</p>
          <p v-else-if="!creationModeOptions.length" class="dict-placeholder">暂无数据</p>
          <div v-else class="chip-group">
            <template v-for="opt in creationModeOptions" :key="opt.value">
              <a-tooltip
                v-if="isCreationModeOptionDisabled(opt.value)"
                title="解说漫暂不支持该创作模式"
              >
                <span class="chip-tooltip-wrap">
                  <button
                    type="button"
                    class="chip is-disabled"
                    :class="{ active: displayCreationMode === opt.value }"
                    disabled
                  >
                    {{ opt.label }}
                  </button>
                </span>
              </a-tooltip>
              <a-tooltip
                v-else-if="skipsStoryboardImageGeneration(opt.value)"
                :title="PRO_MODE_NO_STORYBOARD_IMAGE_TIP"
              >
                <span class="chip-tooltip-wrap">
                  <button
                    type="button"
                    class="chip"
                    :class="{ active: displayCreationMode === opt.value }"
                    @click="pickCreationMode(opt.value)"
                  >
                    {{ opt.label }}
                  </button>
                </span>
              </a-tooltip>
              <button
                v-else
                type="button"
                class="chip"
                :class="{ active: displayCreationMode === opt.value }"
                @click="pickCreationMode(opt.value)"
              >
                {{ opt.label }}
              </button>
            </template>
          </div>
        </div>

      </div>
    </div>

    <div class="right-panel">
      <div class="head_box">
        <img src="../../assets/img/createProcess/Union-r.svg" alt="" />
        <h4 class="block-title">我的风格库</h4>
      </div>
      <GlobalSetting
        v-if="contentReady"
        :model-value="modelValue"
        :style-library-only="true"
        :style-thumb-size-px="107"
        description=""
        @update:model-value="onRightPanelModelUpdate"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import GlobalSetting from '~/components/steps/GlobalSetting.vue'
import type { GlobalSettingData } from '~/types'
import { CREATE_FIRST_STEP_DEFAULTS } from '~/utils/createFirstStepDefaults'
import { DICT_ENUM, usePromptDictionary } from '~/composables/usePromptDictionary'
import {
  buildEnumChipOptions,
  normalizeCreationModeValue,
  normalizeModelStrategyValue,
  normalizeScriptTypeValue,
  type GlobalSettingCreationMode,
  type GlobalSettingModelStrategy,
  type GlobalSettingScriptType
} from '~/utils/globalSettingEnums'
import {
  isCreationModeDisabledForScriptType,
  isScriptTypeLockedToPlot,
  PRO_MODE_NO_STORYBOARD_IMAGE_TIP,
  resolveCreationModeForScriptType,
  skipsStoryboardImageGeneration
} from '~/utils/creationModeUiRules'
import ratio16by9Icon from '~/assets/img/createProcess/16-9.svg'
import ratio9by16Icon from '~/assets/img/createProcess/9-16.svg'
import ratio4by3Icon from '~/assets/img/createProcess/4-3.svg'
import ratio3by4Icon from '~/assets/img/createProcess/3-4.svg'
import ratio1by1Icon from '~/assets/img/createProcess/1-1.svg'
import ratio21by9Icon from '~/assets/img/createProcess/21-9.svg'
import ratio21by9IconSel from '~/assets/img/createProcess/21-9-sel.svg'
import ratio1by1IconSel from '~/assets/img/createProcess/1-1-sel.svg'
import ratio4by3IconSel from '~/assets/img/createProcess/4-3-sel.svg'
import ratio3by4IconSel from '~/assets/img/createProcess/3-4-sel.svg'
import ratio9by16IconSel from '~/assets/img/createProcess/9-16-sel.svg'
import ratio16by9IconSel from '~/assets/img/createProcess/16-9-sel.svg'
import { computed, nextTick, onMounted, reactive, ref, watch } from 'vue'

type RatioValue = '16:9' | '9:16' | '4:3' | '3:4' | '1:1' | '21:9'
type ProjectTypeValue = 'movie' | 'series'
type ScriptTypeValue = GlobalSettingScriptType
type StrategyValue = GlobalSettingModelStrategy
type CreationModeValue = GlobalSettingCreationMode

interface Props {
  open: boolean
  title: string
  projectType: ProjectTypeValue
  aspectRatio: RatioValue
  scriptType: ScriptTypeValue
  modelStrategy: StrategyValue
  creationMode: CreationModeValue
  modelValue: GlobalSettingData
  flowEditMode?: boolean
  projectTypeLocked?: boolean
  syncProjectTypeFromParent?: boolean
  /** 页面内嵌布局（非弹窗） */
  pageLayout?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  flowEditMode: false,
  projectTypeLocked: false,
  syncProjectTypeFromParent: false,
  pageLayout: false
})

const emit = defineEmits<{
  'update:title': [value: string]
  'update:projectType': [value: ProjectTypeValue]
  'update:aspectRatio': [value: RatioValue]
  'update:scriptType': [value: ScriptTypeValue]
  'update:modelStrategy': [value: StrategyValue]
  'update:creationMode': [value: CreationModeValue]
  'update:modelValue': [value: GlobalSettingData]
}>()

type EnumOption = { value: string; label: string }

const projectTypeOptions = ref<Array<{ value: ProjectTypeValue; label: string }>>([
  { value: 'series', label: '剧集' },
  { value: 'movie', label: '电影' }
])

const scriptTypeOptions = ref<Array<{ value: ScriptTypeValue; label: string }>>([])
const creationModeOptions = ref<Array<{ value: CreationModeValue; label: string }>>([])
const modelStrategyOptions = ref<Array<{ value: StrategyValue; label: string }>>([])
const enumOptionsLoaded = ref(false)

const ratioIconByValue: Record<
  RatioValue,
  { icon: string; iconSel: string; label: string }
> = {
  '16:9': { icon: ratio16by9Icon, iconSel: ratio16by9IconSel, label: '16 : 9' },
  '9:16': { icon: ratio9by16Icon, iconSel: ratio9by16IconSel, label: '9 : 16' },
  '4:3': { icon: ratio4by3Icon, iconSel: ratio4by3IconSel, label: '4 : 3' },
  '3:4': { icon: ratio3by4Icon, iconSel: ratio3by4IconSel, label: '3 : 4' },
  '1:1': { icon: ratio1by1Icon, iconSel: ratio1by1IconSel, label: '1 : 1' },
  '21:9': { icon: ratio21by9Icon, iconSel: ratio21by9IconSel, label: '21 : 9' }
}

const ratioOptions = ref<Array<{ label: string; value: RatioValue; icon: string; iconSel: string }>>(
  Object.entries(ratioIconByValue).map(([value, meta]) => ({
    value: value as RatioValue,
    label: meta.label,
    icon: meta.icon,
    iconSel: meta.iconSel
  }))
)

function groupOptions(groups: { enumType: string; items: { value: string; desc: string }[] }[], enumType: string): EnumOption[] {
  return buildEnumChipOptions(groups, enumType)
}

const isNewProjectModal = computed(() => !props.flowEditMode)
const leftPanelReady = ref(false)

const contentReady = computed(
  () => props.open && (props.flowEditMode || props.pageLayout || leftPanelReady.value)
)

const leftPanelDraft = reactive({
  projectType: CREATE_FIRST_STEP_DEFAULTS.projectType as ProjectTypeValue,
  scriptType: CREATE_FIRST_STEP_DEFAULTS.scriptType as ScriptTypeValue,
  modelStrategy: CREATE_FIRST_STEP_DEFAULTS.modelStrategy as StrategyValue,
  creationMode: CREATE_FIRST_STEP_DEFAULTS.creationMode as CreationModeValue
})

const displayProjectType = computed(() =>
  isNewProjectModal.value ? leftPanelDraft.projectType : props.projectType
)
const displayScriptType = computed(() =>
  isNewProjectModal.value ? leftPanelDraft.scriptType : props.scriptType
)
const displayModelStrategy = computed(() =>
  isNewProjectModal.value ? leftPanelDraft.modelStrategy : props.modelStrategy
)
const displayCreationMode = computed(() =>
  isNewProjectModal.value ? leftPanelDraft.creationMode : props.creationMode
)

const PROJECT_TYPE_ORDER: ProjectTypeValue[] = ['series', 'movie']

function sortOptionsByOrder<T extends { value: string }>(options: T[], order: readonly string[]): T[] {
  return [...options].sort((a, b) => {
    const ai = order.indexOf(a.value)
    const bi = order.indexOf(b.value)
    return (ai === -1 ? order.length : ai) - (bi === -1 ? order.length : bi)
  })
}

const { ensureLoaded: ensureDictLoaded, enumList } = usePromptDictionary()

/** 复用风格库同一套字典缓存，与 GlobalSetting.ensureLoaded 合并为一次 enum/list */
async function loadCreateModalEnums() {
  enumOptionsLoaded.value = false
  try {
    await ensureDictLoaded()
    const groups = enumList.value

    const projectTypes = groupOptions(groups, DICT_ENUM.ProjectTypeEnum)
      .map((o) => {
        if (o.value === 'series') return { value: 'series' as const, label: '剧集' }
        if (o.value === 'movie') return { value: 'movie' as const, label: '电影' }
        return null
      })
      .filter(Boolean) as Array<{ value: ProjectTypeValue; label: string }>
    if (projectTypes.length) {
      projectTypeOptions.value = sortOptionsByOrder(projectTypes, PROJECT_TYPE_ORDER)
    }

    const aspectRatios = groupOptions(groups, DICT_ENUM.AspectRatioEnum)
      .map((o) => (o.value in ratioIconByValue ? (o.value as RatioValue) : null))
      .filter(Boolean) as RatioValue[]
    if (aspectRatios.length) {
      ratioOptions.value = aspectRatios.map((v) => {
        const meta = ratioIconByValue[v]
        return { value: v, label: meta.label, icon: meta.icon, iconSel: meta.iconSel }
      })
    }

    const scripts = groupOptions(groups, DICT_ENUM.ScriptTypeEnum)
      .map((o) => {
        const value = normalizeScriptTypeValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: ScriptTypeValue; label: string }>
    if (scripts.length) scriptTypeOptions.value = scripts

    const creations = groupOptions(groups, DICT_ENUM.CreationModeEnum)
      .map((o) => {
        const value = normalizeCreationModeValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: CreationModeValue; label: string }>
    if (creations.length) creationModeOptions.value = creations

    const genModes = groupOptions(groups, DICT_ENUM.GenModeEnum)
      .map((o) => {
        const value = normalizeModelStrategyValue(o.value)
        return value ? { value, label: o.label } : null
      })
      .filter(Boolean) as Array<{ value: StrategyValue; label: string }>
    if (genModes.length) modelStrategyOptions.value = genModes
  } catch {
    scriptTypeOptions.value = []
    creationModeOptions.value = []
    modelStrategyOptions.value = []
  } finally {
    enumOptionsLoaded.value = true
    if (props.open && !props.flowEditMode && !props.pageLayout) initNewProjectLeftPanel()
  }
}

function resetLeftPanelDraft() {
  const d = CREATE_FIRST_STEP_DEFAULTS
  leftPanelDraft.projectType = d.projectType
  leftPanelDraft.scriptType = d.scriptType
  leftPanelDraft.modelStrategy = d.modelStrategy
  leftPanelDraft.creationMode = d.creationMode
}

function applyParentProjectType() {
  if (!props.syncProjectTypeFromParent) return
  const pt = props.projectType
  if (pt === 'series' || pt === 'movie') {
    leftPanelDraft.projectType = pt
  }
}

function syncLeftPanelToParent() {
  emit('update:projectType', leftPanelDraft.projectType)
  emit('update:scriptType', leftPanelDraft.scriptType)
  emit('update:modelStrategy', leftPanelDraft.modelStrategy)
  emit('update:creationMode', leftPanelDraft.creationMode)
}

async function initNewProjectLeftPanel() {
  resetLeftPanelDraft()
  applyParentProjectType()
  syncLeftPanelToParent()
}

function onRightPanelModelUpdate(next: GlobalSettingData) {
  emit('update:modelValue', {
    selectedStyle: next.selectedStyle,
    myStyles: next.myStyles,
    style: next.style,
    styleSelectionTouched: next.styleSelectionTouched,
    styleLocked: next.styleLocked
  } as GlobalSettingData)
}

function pickProjectType(v: ProjectTypeValue) {
  if (isNewProjectModal.value) leftPanelDraft.projectType = v
  emit('update:projectType', v)
}

function pickScriptType(v: ScriptTypeValue) {
  if (isNewProjectModal.value) leftPanelDraft.scriptType = v
  emit('update:scriptType', v)
  const nextMode = resolveCreationModeForScriptType(displayCreationMode.value, v)
  if (nextMode !== displayCreationMode.value) {
    if (isNewProjectModal.value) leftPanelDraft.creationMode = nextMode
    emit('update:creationMode', nextMode)
  }
}

function pickModelStrategy(v: StrategyValue) {
  if (isNewProjectModal.value) leftPanelDraft.modelStrategy = v
  emit('update:modelStrategy', v)
}

function pickCreationMode(v: CreationModeValue) {
  if (isCreationModeOptionDisabled(v)) return
  if (isNewProjectModal.value) leftPanelDraft.creationMode = v
  emit('update:creationMode', v)
  if (isScriptTypeLockedToPlot(v) && displayScriptType.value !== 'plot') {
    if (isNewProjectModal.value) leftPanelDraft.scriptType = 'plot'
    emit('update:scriptType', 'plot')
  }
}

function isScriptTypeOptionDisabled(value: ScriptTypeValue): boolean {
  return isScriptTypeLockedToPlot(displayCreationMode.value) && value === 'monologue'
}

function isCreationModeOptionDisabled(value: CreationModeValue): boolean {
  return isCreationModeDisabledForScriptType(value, displayScriptType.value)
}

function ensureEnumSelection<T extends string>(
  current: T,
  options: Array<{ value: T }>,
  emitUpdate: (v: T) => void,
  normalize?: (raw: string) => T | null
) {
  if (!options.length) return
  const normalized = normalize ? normalize(String(current)) : null
  if (normalized && options.some((o) => o.value === normalized)) {
    if (normalized !== current) emitUpdate(normalized)
    return
  }
  if (options.some((o) => o.value === current)) return
  emitUpdate(options[0]!.value)
}

const hoveredRatio = ref<RatioValue | null>(null)

function ratioIconSrc(ratio: { value: RatioValue; icon: string; iconSel: string }) {
  const selected = props.aspectRatio === ratio.value
  const hover = hoveredRatio.value === ratio.value
  return selected || hover ? ratio.iconSel : ratio.icon
}

const onTitleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  emit('update:title', target.value)
}

onMounted(() => {
  void loadCreateModalEnums()
})

watch(
  [() => props.modelStrategy as unknown as string, () => modelStrategyOptions.value],
  ([current, options]) => {
    if (props.flowEditMode) {
      ensureEnumSelection(current as StrategyValue, options, (v) => emit('update:modelStrategy', v), normalizeModelStrategyValue)
    }
  },
  { immediate: true }
)

watch(
  [() => props.scriptType, () => scriptTypeOptions.value],
  ([current, options]) => {
    if (props.flowEditMode) {
      ensureEnumSelection(current, options, (v) => emit('update:scriptType', v), normalizeScriptTypeValue)
    }
  },
  { immediate: true }
)

watch(
  [() => props.creationMode, () => creationModeOptions.value, () => displayScriptType.value],
  ([current, options, scriptType]) => {
    if (props.flowEditMode) {
      ensureEnumSelection(current, options, (v) => emit('update:creationMode', v), normalizeCreationModeValue)
    }
    const resolved = resolveCreationModeForScriptType(current, scriptType)
    if (resolved !== current) {
      if (isNewProjectModal.value) leftPanelDraft.creationMode = resolved
      emit('update:creationMode', resolved)
      return
    }
    if (isScriptTypeLockedToPlot(current) && displayScriptType.value !== 'plot') {
      if (isNewProjectModal.value) leftPanelDraft.scriptType = 'plot'
      emit('update:scriptType', 'plot')
    }
  },
  { immediate: true }
)

watch(
  () => props.open,
  async (isOpen) => {
    if (!isOpen) {
      leftPanelReady.value = false
      return
    }
    if (props.flowEditMode || props.pageLayout) {
      leftPanelReady.value = true
      return
    }
    leftPanelReady.value = false
    await nextTick()
    await initNewProjectLeftPanel()
    await nextTick()
    leftPanelReady.value = true
  },
  { immediate: true }
)
</script>

<style lang="scss" scoped>
.create-first-step-form {
  display: grid;
  grid-template-columns: 324px 1fr;
  gap: 16px;
  min-height: 0;
}

.create-first-step-form--page {
  flex: 1;
  min-height: 0;
  height: 100%;
  grid-template-columns: minmax(280px, 340px) 1fr;
  align-content: stretch;
}

.left-panel,
.right-panel {
  border: 1px solid rgba(74, 231, 253, 0.22);
  background: rgba(8, 12, 22, 0.72);
  border-radius: 10px;
  box-sizing: border-box;
  overflow: hidden;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.create-first-step-form--page .left-panel,
.create-first-step-form--page .right-panel {
  border-color: rgba(74, 231, 253, 0.15);
  background: rgba(6, 10, 18, 0.55);
  height: 100%;
}

.content_box {
  padding: 10px 14px 12px;
  overflow-y: auto;
  flex: 1;
  min-height: 0;
}

.head_box {
  height: 40px;
  width: 100%;
  background: rgba(32, 36, 52, 0.85);
  display: flex;
  align-items: center;
  gap: 6px;
  padding-left: 16px;
  border-bottom: 1px solid rgba(74, 231, 253, 0.2);
  flex-shrink: 0;

  .block-title {
    font-size: 15px;
    margin-bottom: 0;
    line-height: 22px;
    color: var(--home-text, #e6edf3);
    font-weight: 600;
  }
}

.field-group {
  margin-bottom: 14px;

  .chip-group {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;

    .chip {
      border: 1px solid rgba(74, 231, 253, 0.25);
      background: rgba(255, 255, 255, 0.02);
      color: var(--home-muted, #8e97a5) !important;
      border-radius: 6px;
      padding: 0 10px;
      cursor: pointer;
      font-size: 12px;
      line-height: 26px;
      box-sizing: border-box;
      transition: all 0.2s ease;

      &.is-disabled {
        opacity: 0.45;
        cursor: not-allowed;
        pointer-events: none;
      }
    }

    .chip-tooltip-wrap {
      display: inline-flex;
    }

    .chip.active,
    .chip:hover {
      color: var(--home-accent, #4ae7fd) !important;
      border-color: var(--home-accent, #4ae7fd);
      background: rgba(74, 231, 253, 0.08);
    }
  }

  .name-input-wrap {
    position: relative;

    .name-input {
      width: 100%;
      height: 36px;
      border-radius: 6px;
      border: 1px solid rgba(74, 231, 253, 0.15);
      background: rgba(0, 0, 0, 0.35);
      color: var(--home-text, #e6edf3) !important;
      padding: 0 58px 0 12px;
      font-size: 14px;
      line-height: 20px;
      outline: none;
      transition: border-color 0.2s ease;

      &:focus {
        border-color: rgba(74, 231, 253, 0.45);
      }
    }

    .count-text {
      position: absolute;
      right: 10px;
      top: 8px;
      font-size: 12px;
      color: var(--home-muted, #8e97a5) !important;
    }
  }

  .ratio-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 8px;

    .ratio-item {
      transition: all 0.2s ease;

      span {
        color: var(--home-muted, #8e97a5) !important;
      }
    }

    .ratio-item:hover,
    .ratio-item.active {
      border-color: var(--home-accent, #4ae7fd);
      background: rgba(74, 231, 253, 0.06);

      span {
        color: var(--home-accent, #4ae7fd) !important;
      }
    }
  }
}

.field-label {
  display: block;
  font-size: 13px;
  margin-bottom: 8px;
  color: var(--home-text, #e6edf3);
  font-weight: 500;
}

.ratio-item {
  border: 1px solid rgba(74, 231, 253, 0.25);
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.02);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 5px 6px;
  cursor: pointer;
  min-height: 28px;
  font-size: 12px;
  line-height: 16px;
}

.ratio-item img {
  width: 16px;
  height: 16px;
}

.right-panel :deep(.global-setting) {
  padding: 0;
  flex: 1 1 0;
  min-height: 0;
  height: 0;
  overflow-y: auto;
  padding-right: 4px;
}

.right-panel :deep(.setting-sections) {
  gap: 12px;
  padding: 8px 12px 12px;
}

.right-panel :deep(.my-styles .subsection-title.title-one) {
  display: none;
}

.right-panel :deep(.my-styles) {
  margin-bottom: 8px;
}

.right-panel :deep(.featured-styles--collapsed) {
  flex-shrink: 0;
}

.right-panel :deep(.featured-styles--collapsed .styles-grid) {
  overflow: visible;
  padding-bottom: 4px;
}

.right-panel :deep(.section-title) {
  font-size: 14px;
  margin-bottom: 10px;
}

.right-panel :deep(.styles-grid) {
  grid-template-columns: repeat(6, minmax(0, 1fr));
  gap: 8px;
}

.right-panel :deep(.style-card) {
  aspect-ratio: 1;
  width: 100%;
  height: auto;
}

.right-panel :deep(.style-card.add-style) {
  border-style: dashed;
  border-color: rgba(74, 231, 253, 0.3);
  background: #151724;

  span {
    color: #8e97a5 !important;
  }

  :deep(.add-text) {
    color: #8e97a5 !important;
  }

  :deep(.add-icon) {
    color: #8e97a5 !important;
  }

  :deep(.add-icon svg),
  :deep(.add-icon svg path) {
    fill: currentColor !important;
  }
}

.dict-placeholder {
  margin: 0 0 8px;
  font-size: 12px;
  color: #8e97a5;
}
</style>
