// components/steps/ImportSceneImageModal.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { Button, Modal, message } from 'antd'
import { UploadOutlined, FolderOutlined, FileTextOutlined, CloseOutlined } from '@ant-design/icons'
import ModalTitleWatermark from '~/components/ModalTitleWatermark'
import ImportScriptModal from './ImportScriptModal'
import { useCreationStore } from '~/stores/creation'
import { userAssetRpsFormList, userProjectList } from '~/utils/businessApi'
import type { UserAssetApiType } from '~/types/business-api'
import { assetUrl } from '~/utils/assetUrl'
import PreviewableImageThumb from '~/components/common/PreviewableImageThumb'
import noDataRaw from '@/assets/img/icon/no_data.svg'
import emptyIconRaw from '@/assets/img/icon/empty_icon.svg'
import dialogSelectNorRaw from '@/assets/img/icon/dialog-select-nor.svg'
import dialogSelectSelRaw from '@/assets/img/icon/dialog-select-sel.svg'
import './ImportSceneImageModal.css'

const noDataIconUrl = assetUrl(noDataRaw)
const emptyIconUrl = assetUrl(emptyIconRaw)
const dialogSelectNorIcon = assetUrl(dialogSelectNorRaw)
const dialogSelectSelIcon = assetUrl(dialogSelectSelRaw)

export interface ImportSceneImageModalProps {
  open: boolean
  assetType?: UserAssetApiType
  title?: string
  onOpenChange: (open: boolean) => void
  onImport: (asset: File | string | Record<string, any>) => void
}

const titleMap: Record<string, string> = {
  scene: '导入场景',
  character: '导入角色',
  prop: '导入道具'
}

const countLabelMap: Record<string, string> = {
  scene: '场景数',
  character: '角色数',
  prop: '道具数'
}

function pickThumb(form: any): string {
  const imgs = Array.isArray(form?.images) ? form.images : []
  const inUse = imgs.find((x: any) => Number(x?.isUse) === 1)
  const latest = imgs[0]
  return inUse?.imageUrl || latest?.imageUrl || form?.imageUrl || ''
}

export function ImportSceneImageModal({
  open,
  assetType = 'scene',
  title = '导入场景',
  onOpenChange,
  onImport
}: ImportSceneImageModalProps) {
  const [activeSubTab, setActiveSubTab] = useState<'current' | 'history'>('current')
  const [selectedAsset, setSelectedAsset] = useState<any>(null)
  const [selectedSceneId, setSelectedSceneId] = useState<string | null>(null)
  const [showAssetLibraryModal, setShowAssetLibraryModal] = useState(false)
  const [scenesList, setScenesList] = useState<any[]>([])
  const [loading, setLoading] = useState(false)

  const countLabel = countLabelMap[assetType] || '资产数'

  async function loadCurrentAssets(): Promise<any[]> {
    const creationStore = useCreationStore.getState()
    const projectId = creationStore.currentProjectId
    if (!projectId) {
      return []
    }
    const payload: Record<string, any> = {
      projectId,
      assetType
    }
    if (creationStore.currentEpisodeId != null && creationStore.currentEpisodeId >= 0) {
      payload.episodeId = creationStore.currentEpisodeId
    }
    const rows = await userAssetRpsFormList(payload as any)
    return rows
      .map((row: any, index: number) => {
        const thumbnail = pickThumb(row)
        return {
          id: `current-${row.id}-${index}`,
          name: row.name || `${countLabel.replace('数', '')}${index + 1}`,
          thumbnail,
          url: thumbnail,
          rpsFormId: row.id,
          rpsImageId: row.currentImageId,
          type: assetType
        }
      })
      .filter((x: any) => !!x.thumbnail)
  }

  async function loadHistoryAssets(): Promise<any[]> {
    const { rows: projects } = await userProjectList({ pageNum: 1, pageSize: 50 })
    const currentProjectId = Number(useCreationStore.getState().currentProjectId || 0)
    const historyProjects = (projects || []).filter((p) => Number(p.id) !== currentProjectId)
    if (!historyProjects.length) {
      return []
    }
    const formBatches = await Promise.all(
      historyProjects.map(async (p) => {
        try {
          const forms = await userAssetRpsFormList({
            projectId: Number(p.id),
            assetType
          } as any)
          return forms.map((f: any, index: number) => {
            const thumbnail = pickThumb(f)
            return {
              id: `history-${p.id}-${f.id}-${index}`,
              name: f.name || `${countLabel.replace('数', '')}${index + 1}`,
              thumbnail,
              url: thumbnail,
              projectName: p.projectName || `项目${p.id}`,
              rpsFormId: f.id,
              rpsImageId: f.currentImageId,
              type: assetType
            }
          })
        } catch {
          return []
        }
      })
    )
    return formBatches.flat().filter((x: any) => !!x.thumbnail)
  }

  async function loadScenesByTab(tab: 'current' | 'history') {
    setLoading(true)
    try {
      const list = tab === 'current' ? await loadCurrentAssets() : await loadHistoryAssets()
      setScenesList(list)
    } catch (e: any) {
      setScenesList([])
      message.error(e?.msg || e?.message || `${titleMap[assetType] || '资产'}加载失败`)
    } finally {
      setLoading(false)
    }
  }

  const selectScene = (scene: any) => {
    setSelectedSceneId(scene.id)
    setSelectedAsset({ ...scene, type: assetType })
    message.success(`${titleMap[assetType] || '资产'}已选择`)
  }

  const handleSelectLocalFile = () => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = 'image/*'
    input.onchange = (e: Event) => {
      const t = e.target as HTMLInputElement
      const file = t.files?.[0]
      if (file) {
        onImport(file)
        onOpenChange(false)
        setSelectedAsset(null)
        setSelectedSceneId(null)
        setShowAssetLibraryModal(false)
        message.success('导入成功')
      }
    }
    input.click()
  }

  const handleOpenAssetLibrary = () => {
    setShowAssetLibraryModal(true)
  }

  const handleDirectImport = (asset: any) => {
    if (typeof asset === 'string') {
      onImport(asset)
    } else if (asset && asset.type === 'image') {
      onImport(asset)
    } else {
      onImport(asset)
    }
    setShowAssetLibraryModal(false)
    onOpenChange(false)
    setSelectedAsset(null)
    setSelectedSceneId(null)
    message.success('导入成功')
  }

  const handleConfirm = () => {
    if (!selectedAsset) {
      message.warning('请选择要导入的图片或场景')
      return
    }

    if (selectedAsset.type === 'local') {
      onImport(selectedAsset.file)
    } else if (selectedAsset.type === 'library') {
      const assetObj = selectedAsset.url
        ? { url: selectedAsset.url, name: selectedAsset.name || '导入的图片' }
        : { ...selectedAsset }
      onImport(assetObj)
    } else if (
      selectedAsset.type === 'scene' ||
      selectedAsset.type === 'character' ||
      selectedAsset.type === 'prop'
    ) {
      onImport(selectedAsset)
    }

    onOpenChange(false)
    setSelectedAsset(null)
    setSelectedSceneId(null)
    message.success('导入成功')
  }

  const handleCancel = () => {
    onOpenChange(false)
    setSelectedAsset(null)
    setSelectedSceneId(null)
    setShowAssetLibraryModal(false)
  }

  useEffect(() => {
    if (!open) return
    setSelectedAsset(null)
    setSelectedSceneId(null)
    void loadScenesByTab(activeSubTab)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  const tabMountedRef = useRef(false)
  useEffect(() => {
    // 原 watch(activeSubTab) 非 immediate：跳过首次执行
    if (!tabMountedRef.current) {
      tabMountedRef.current = true
      return
    }
    if (!open) return
    setSelectedAsset(null)
    setSelectedSceneId(null)
    void loadScenesByTab(activeSubTab)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeSubTab])

  return (
    <Modal
      open={open}
      width={1100}
      footer={null}
      title={null}
      closable={false}
      centered
      className="import-scene-image-modal"
      wrapClassName="create-flow-modal import-scene-image-modal-wrap"
      onCancel={handleCancel}
    >
      <div className="import-scene-shell">
        <header className="import-scene-header">
          <ModalTitleWatermark title={title} watermark="IMPORT" />
          <button type="button" className="import-scene-close" aria-label="关闭" onClick={handleCancel}>
            <CloseOutlined />
          </button>
        </header>

        <div className="import-body">
          <div className="import-tab-bar">
            <div></div>
            <div className="import-tab-bar__inner">
              <button
                type="button"
                className={`import-tab${activeSubTab === 'current' ? ' import-tab--active' : ''}`}
                onClick={() => setActiveSubTab('current')}
              >
                本作品资产
              </button>
              <button
                type="button"
                className={`import-tab${activeSubTab === 'history' ? ' import-tab--active' : ''}`}
                onClick={() => setActiveSubTab('history')}
              >
                历史作品资产
              </button>
            </div>
            <span className="import-tab-bar__count">
              {countLabel}：{scenesList.length}项
            </span>
          </div>

          <div className="import-content">
            {loading ? (
              <div className="import-empty">
                <img src={noDataIconUrl} alt="" />
                <p className="import-empty__text">加载中...</p>
              </div>
            ) : scenesList.length > 0 ? (
              <div className="import-scenes-row" role="listbox" aria-label="可导入图片">
                {scenesList.map((scene) => {
                  const selected = selectedSceneId === scene.id
                  return (
                    <article
                      key={scene.id}
                      className={`import-scene-card${selected ? ' import-scene-card--selected' : ''}`}
                      role="option"
                      aria-selected={selected}
                      tabIndex={0}
                      onClick={() => selectScene(scene)}
                      onKeyDown={(event) => {
                        if (event.key !== 'Enter' && event.key !== ' ') return
                        event.preventDefault()
                        selectScene(scene)
                      }}
                    >
                      <div className="import-scene-card__thumb">
                        {scene.thumbnail ? (
                          <PreviewableImageThumb
                            src={scene.thumbnail}
                            alt={scene.name}
                            title={scene.name}
                            objectFit="contain"
                          />
                        ) : (
                          <div className="import-scene-card__placeholder">
                            <FileTextOutlined />
                          </div>
                        )}
                      </div>
                      <div className="import-scene-card__label">
                        <span className="import-scene-card__name">{scene.name}</span>
                      </div>
                      <button
                        type="button"
                        className="import-scene-card__select"
                        aria-label={selected ? `已选择${scene.name}` : `选择${scene.name}`}
                        aria-pressed={selected}
                        onClick={(event) => {
                          event.stopPropagation()
                          selectScene(scene)
                        }}
                      >
                        <img
                          src={selected ? dialogSelectSelIcon : dialogSelectNorIcon}
                          alt=""
                          aria-hidden="true"
                        />
                      </button>
                    </article>
                  )
                })}
              </div>
            ) : (
              <div className="import-empty">
                <img src={emptyIconUrl} alt="" />
                <p className="import-empty__text">暂无可导入资产</p>
              </div>
            )}
          </div>
        </div>

        <div className="import-footer">
          <div className="import-footer__left">
            <Button className="import-btn-dashed" icon={<UploadOutlined />} onClick={handleSelectLocalFile}>
              选择本地文件
            </Button>
            <Button className="import-btn-dashed" icon={<FolderOutlined />} onClick={handleOpenAssetLibrary}>
              资产库导入
            </Button>
          </div>
          <div className="import-footer__right">
            <Button className="import-btn-cancel" size="large" onClick={handleCancel}>
              <div className="text-gradient">取消</div>
            </Button>
            <Button
              type="primary"
              size="large"
              className="import-btn-ok"
              disabled={!selectedAsset}
              onClick={handleConfirm}
            >
              确定
            </Button>
          </div>
        </div>
      </div>

      <ImportScriptModal
        open={showAssetLibraryModal}
        onOpenChange={setShowAssetLibraryModal}
        title="导入图片"
        onImport={handleDirectImport}
      />
    </Modal>
  )
}

export default ImportSceneImageModal

// components/steps/ImportSceneImageModal.vue
<template>
  <a-modal
    v-model:open="modalOpen"
    :width="1100"
    :footer="null"
    :title="null"
    :closable="false"
    centered
    class="import-scene-image-modal"
    wrap-class-name="create-flow-modal import-scene-image-modal-wrap"
    @cancel="handleCancel"
  >
    <div class="import-scene-shell">
      <header class="import-scene-header">
        <ModalTitleWatermark :title="props.title" watermark="IMPORT" />
        <button type="button" class="import-scene-close" aria-label="关闭" @click="handleCancel">
          <CloseOutlined />
        </button>
      </header>

      <div class="import-body">
      <div class="import-tab-bar">
        <div></div>
        <div class="import-tab-bar__inner">
          <button
            type="button"
            :class="['import-tab', { 'import-tab--active': activeSubTab === 'current' }]"
            @click="activeSubTab = 'current'"
          >
            本作品资产
          </button>
          <button
            type="button"
            :class="['import-tab', { 'import-tab--active': activeSubTab === 'history' }]"
            @click="activeSubTab = 'history'"
          >
            历史作品资产
          </button>
        </div>
        <span class="import-tab-bar__count">{{ countLabel }}：{{ scenesList.length }}项</span>
      </div>

      <div class="import-content">
        <div v-if="loading" class="import-empty">
          <img src="@/assets/img/icon/no_data.svg" alt="">
          <p class="import-empty__text">加载中...</p>
        </div>
        <div v-else-if="scenesList.length > 0" class="import-scenes-row">
          <button
            v-for="scene in scenesList"
            :key="scene.id"
            type="button"
            :class="[
              'import-scene-card',
              { 'import-scene-card--selected': selectedSceneId === scene.id }
            ]"
            @click="selectScene(scene)"
          >
            <div class="import-scene-card__thumb">
              <img v-if="scene.thumbnail" :src="scene.thumbnail" :alt="scene.name" />
              <div v-else class="import-scene-card__placeholder">
                <FileTextOutlined />
              </div>
            </div>
            <div class="import-scene-card__label">
              <span class="import-scene-card__name">{{ scene.name }}</span>
            </div>
          </button>
        </div>
        <div v-else class="import-empty">
          <img src="@/assets/img/icon/empty_icon.svg" alt="">
          <p class="import-empty__text">暂无可导入资产</p>
        </div>
      </div>
    </div>

    <div class="import-footer">
      <div class="import-footer__left">
        <a-button class="import-btn-dashed" @click="handleSelectLocalFile">
          <template #icon><UploadOutlined /></template>
          选择本地文件
        </a-button>
        <a-button class="import-btn-dashed" @click="handleOpenAssetLibrary">
          <template #icon><FolderOutlined /></template>
          资产库导入
        </a-button>
      </div>
      <div class="import-footer__right">
        <a-button class="import-btn-cancel" size="large" @click="handleCancel">
          <div class="text-gradient">取消</div>
        </a-button>
        <a-button
          type="primary"
          size="large"
          class="import-btn-ok"
          :disabled="!selectedAsset"
          @click="handleConfirm"
        >
          确定
        </a-button>
      </div>
    </div>
    </div>

    <ImportScriptModal
      v-model:open="showAssetLibraryModal"
      title="导入图片"
      @import="handleDirectImport"
    />
  </a-modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import {
  UploadOutlined,
  FolderOutlined,
  FileTextOutlined,
  CloseOutlined
} from '@ant-design/icons-vue'
import ModalTitleWatermark from '~/components/ModalTitleWatermark.vue'
import ImportScriptModal from './ImportScriptModal.vue'
import { useCreationStore } from '~/stores/creation'
import { userAssetRpsFormList, userProjectList } from '~/utils/businessApi'
import type { UserAssetApiType } from '~/types/business-api'

interface Props {
  open: boolean
  assetType?: UserAssetApiType
  title?: string
}

const props = withDefaults(defineProps<Props>(), {
  assetType: 'scene',
  title: '导入场景'
})

const emit = defineEmits<{
  'update:open': [value: boolean]
  import: [file: File | string]
}>()

const modalOpen = computed({
  get: () => props.open,
  set: (value) => emit('update:open', value)
})

const activeSubTab = ref<'current' | 'history'>('current')
const selectedAsset = ref<any>(null)
const selectedSceneId = ref<string | null>(null)
const showAssetLibraryModal = ref(false)
const scenesList = ref<any[]>([])
const loading = ref(false)
const creationStore = useCreationStore()

const titleMap: Record<string, string> = {
  scene: '导入场景',
  character: '导入角色',
  prop: '导入道具'
}

const countLabelMap: Record<string, string> = {
  scene: '场景数',
  character: '角色数',
  prop: '道具数'
}

const countLabel = computed(() => countLabelMap[props.assetType] || '资产数')

function pickThumb(form: any): string {
  const imgs = Array.isArray(form?.images) ? form.images : []
  const inUse = imgs.find((x: any) => Number(x?.isUse) === 1)
  const latest = imgs[0]
  return inUse?.imageUrl || latest?.imageUrl || form?.imageUrl || ''
}

async function loadCurrentAssets() {
  const projectId = creationStore.currentProjectId
  if (!projectId) {
    scenesList.value = []
    return
  }
  const payload: Record<string, any> = {
    projectId,
    assetType: props.assetType
  }
  if (creationStore.currentEpisodeId != null && creationStore.currentEpisodeId >= 0) {
    payload.episodeId = creationStore.currentEpisodeId
  }
  const rows = await userAssetRpsFormList(payload)
  scenesList.value = rows
    .map((row, index) => {
      const thumbnail = pickThumb(row)
      return {
        id: `current-${row.id}-${index}`,
        name: row.name || `${countLabel.value.replace('数', '')}${index + 1}`,
        thumbnail,
        url: thumbnail,
        rpsFormId: row.id,
        rpsImageId: row.currentImageId,
        type: props.assetType
      }
    })
    .filter((x) => !!x.thumbnail)
}

async function loadHistoryAssets() {
  const { rows: projects } = await userProjectList({ pageNum: 1, pageSize: 50 })
  const currentProjectId = Number(creationStore.currentProjectId || 0)
  const historyProjects = (projects || []).filter((p) => Number(p.id) !== currentProjectId)
  if (!historyProjects.length) {
    scenesList.value = []
    return
  }
  const formBatches = await Promise.all(
    historyProjects.map(async (p) => {
      try {
        const forms = await userAssetRpsFormList({
          projectId: Number(p.id),
          assetType: props.assetType
        })
        return forms.map((f, index) => {
          const thumbnail = pickThumb(f)
          return {
            id: `history-${p.id}-${f.id}-${index}`,
            name: f.name || `${countLabel.value.replace('数', '')}${index + 1}`,
            thumbnail,
            url: thumbnail,
            projectName: p.projectName || `项目${p.id}`,
            rpsFormId: f.id,
            rpsImageId: f.currentImageId,
            type: props.assetType
          }
        })
      } catch {
        return []
      }
    })
  )
  scenesList.value = formBatches.flat().filter((x) => !!x.thumbnail)
}

async function loadScenesByTab() {
  loading.value = true
  try {
    if (activeSubTab.value === 'current') await loadCurrentAssets()
    else await loadHistoryAssets()
  } catch (e: any) {
    scenesList.value = []
    message.error(e?.msg || e?.message || `${titleMap[props.assetType] || '资产'}加载失败`)
  } finally {
    loading.value = false
  }
}

const selectScene = (scene: any) => {
  selectedSceneId.value = scene.id
  selectedAsset.value = { ...scene, type: props.assetType }
  message.success(`${titleMap[props.assetType] || '资产'}已选择`)
}

const handleSelectLocalFile = () => {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = 'image/*'
  input.onchange = (e: Event) => {
    const t = e.target as HTMLInputElement
    const file = t.files?.[0]
    if (file) {
      emit('import', file)
      modalOpen.value = false
      selectedAsset.value = null
      selectedSceneId.value = null
      showAssetLibraryModal.value = false
      message.success('导入成功')
    }
  }
  input.click()
}

const handleOpenAssetLibrary = () => {
  showAssetLibraryModal.value = true
}

const handleDirectImport = (asset: any) => {
  if (typeof asset === 'string') {
    emit('import', asset)
  } else if (asset && asset.type === 'image') {
    emit('import', asset)
  } else {
    emit('import', asset)
  }
  showAssetLibraryModal.value = false
  modalOpen.value = false
  selectedAsset.value = null
  selectedSceneId.value = null
  message.success('导入成功')
}

const handleConfirm = () => {
  if (!selectedAsset.value) {
    message.warning('请选择要导入的图片或场景')
    return
  }

  if (selectedAsset.value.type === 'local') {
    emit('import', selectedAsset.value.file)
  } else if (selectedAsset.value.type === 'library') {
    const assetObj = selectedAsset.value.url
      ? { url: selectedAsset.value.url, name: selectedAsset.value.name || '导入的图片' }
      : { ...selectedAsset.value }
    emit('import', assetObj)
  } else if (selectedAsset.value.type === 'scene' || selectedAsset.value.type === 'character' || selectedAsset.value.type === 'prop') {
    emit('import', selectedAsset.value)
  }

  modalOpen.value = false
  selectedAsset.value = null
  selectedSceneId.value = null
  message.success('导入成功')
}

const handleCancel = () => {
  modalOpen.value = false
  selectedAsset.value = null
  selectedSceneId.value = null
  showAssetLibraryModal.value = false
}

watch(
  () => props.open,
  (open) => {
    if (!open) return
    selectedAsset.value = null
    selectedSceneId.value = null
    void loadScenesByTab()
  }
)

watch(
  () => activeSubTab.value,
  () => {
    if (!props.open) return
    selectedAsset.value = null
    selectedSceneId.value = null
    void loadScenesByTab()
  }
)
</script>

<style lang="scss" scoped>
/* 与 BatchRegenerateDubbingModal .brdm 同高 */
.import-scene-shell {
  color: #e6edf3;
  height: 698px;
  max-height: calc(100vh - 80px);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: #191a1d;
}

.import-scene-header {
  position: relative;
  flex-shrink: 0;
  min-height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 12px 48px 8px 16px;
}

.import-scene-close {
  position: absolute;
  top: 50%;
  right: 16px;
  transform: translateY(-50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  padding: 0;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: rgba(255, 255, 255, 0.75);
  cursor: pointer;
  font-size: 16px;

  &:hover {
    color: #4ae7fd;
  }
}

.import-body {
  flex: 1 1 auto;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 0 16px;
  background: #191a1d;
}

.import-subtitle {
  margin: 0 0 1rem;
  font-size: 0.875rem;
  line-height: 1.5;
  color: #8e97a5;
  text-align: center;
}

/* Tab 条：Figma #202434 底条 + 选中青底 */
.import-tab-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  min-height: 40px;
  padding: 6px 0.75rem;
  margin-bottom: 12px;
  border-radius: 8px;
  background: #202434;
  flex-shrink: 0;
}

.import-tab-bar__inner {
  display: flex;
  align-items: center;
  gap: 0;
}

.import-tab {
  position: relative;
  margin: 0;
  padding: 0.35rem 1.1rem;
  border: none;
  border-radius: 8px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  background: transparent;
  color: #ffffff;
  transition:
    color 0.2s ease,
    background 0.2s ease;
}

.import-tab:hover {
  color: #e6edf3;
}
.import-tab-bar {
  .import-tab-bar__inner {
    background: rgba(41, 75, 93,1);
    border-radius: 8px;
    .import-tab--active {
      background: #4ae7fd;
      color: #121212 !important;
    }
  }
}

.import-tab-bar__count {
  flex-shrink: 0;
  font-size: 12px;
  color: #8e97a5;
  font-family: 'PingFang SC', system-ui, sans-serif;
}

.import-content {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
  border-radius: 8px;
}

.import-scenes-row {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 1rem;
  padding: 0.25rem 0 0.5rem;
}

@media (max-width: 900px) {
  .import-scenes-row {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 560px) {
  .import-scenes-row {
    grid-template-columns: 1fr;
  }
}

.import-scene-card {
  position: relative;
  display: block;
  margin: 0;
  padding: 0;
  aspect-ratio: 328 / 154;
  border: 1px solid rgba(0, 0, 0, 0.35);
  border-radius: 8px;
  overflow: hidden;
  cursor: pointer;
  background: #111621;
  transition:
    border-color 0.2s ease,
    box-shadow 0.2s ease;
}

.import-scene-card:hover {
  border-color: rgba(74, 231, 253, 0.45);
  box-shadow: 0 0 0 1px rgba(74, 231, 253, 0.15);
}

.import-scene-card--selected {
  border: 2px solid #4ae7fd;
  box-shadow:
    0 0 0 1px rgba(74, 231, 253, 0.25),
    0 8px 24px rgba(0, 163, 255, 0.12);
}

.import-scene-card__thumb {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background: #111621;
}

.import-scene-card__thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.import-scene-card__placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: rgba(142, 151, 165, 0.6);
  font-size: 2rem;
}

.import-scene-card__label {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 2;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0.45rem 0.5rem;
  background: rgba(18,18,18,.7);
}

.import-scene-card__name {
  font-size: 14px;
  line-height: 1.43;
  color: #ffffff;
  text-align: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 100%;
}

.import-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1 1 auto;
  min-height: 160px;
  color: #8e97a5;
}

.import-empty__icon {
  font-size: 3rem;
  margin-bottom: 0.75rem;
  opacity: 0.65;
}

.import-empty__text {
  margin: 0;
  font-size: 0.9375rem;
}

.import-footer {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  flex-shrink: 0;
  padding: 12px 16px 16px;
  background: #191a1d;
}

.import-footer__left {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}

.import-footer__right {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-left: auto;
}

.import-btn-dashed {
  border-radius: 8px !important;
  border: 1px dashed rgba(74, 231, 253, 0.35) !important;
  background: #121212 !important;
  color: #ffffff !important;
  height: 28px;
  padding: 0 10px !important;
  font-size: 14px !important;
}

.import-btn-dashed:hover {
  border-color: rgba(74, 231, 253, 0.55) !important;
  color: #4ae7fd !important;
}

.import-btn-cancel {
  min-width: 96px;
  border-radius: 10px !important;
  border: 1px solid rgba(74, 231, 253, 0.3) !important;
  background: rgba(18, 18, 18, 1) !important;
  color: #e6edf3 !important;
}

.import-btn-cancel:hover {
  border-color: rgba(74, 231, 253, 0.45) !important;
  color: #4ae7fd !important;
}

.import-btn-ok {
  min-width: 100px;
  border-radius: 10px !important;
  border: none !important;
  font-weight: 600;
  background: linear-gradient(270deg, #0e59fa 0%, #00abd8 100%) !important;
  color: #fff !important;
  box-shadow: none !important;
}

.import-btn-ok:hover:not(:disabled) {
  background: linear-gradient(270deg, #2a6cfb 0%, #4ae7fd 100%) !important;
  color: #fff !important;
}
</style>

<style lang="scss">
.ant-modal-wrap.import-scene-image-modal-wrap .ant-modal.import-scene-image-modal .ant-modal-content {
  padding: 0 !important;
  overflow: hidden;
  border-radius: 12px;
  background: #191a1d;
  box-shadow: 0 24px 64px rgba(0, 0, 0, 0.55);
}

.ant-modal-wrap.import-scene-image-modal-wrap .ant-modal.import-scene-image-modal .ant-modal-header {
  display: none !important;
}

.ant-modal-wrap.import-scene-image-modal-wrap .ant-modal.import-scene-image-modal .ant-modal-body {
  padding: 0 !important;
  background: #191a1d;
}
</style>
