// components/steps/SettingCardImagePopover.vue
<template>
  <div ref="rootRef" class="setting-card-popover-root">
    <div
      ref="triggerRef"
      class="setting-card-popover-trigger"
      :class="{ 'is-disabled': disabled }"
      @click.stop="toggle"
    >
      <slot />
    </div>

    <Teleport to="body">
      <Transition name="setting-card-fade">
        <div
          v-if="open && readyToShowPanel"
          ref="panelRef"
          class="setting-card-panel"
          :class="{ 'is-open-down': !openUpward, 'is-open-up': openUpward }"
          :style="panelStyle"
          role="menu"
          aria-label="生成角色设定卡"
        >
          <a-alert
            v-if="!isSupported"
            type="info"
            show-icon
            message="仅支持角色形态"
            class="setting-card-alert"
          />
          <a-alert
            v-else-if="!isWhiteBaseReady"
            type="warning"
            show-icon
            message="请先在列表中点击自动生成按钮生成图片以后再进行操作"
            class="setting-card-alert"
          />
          <div v-else-if="loading" class="setting-card-empty">加载中…</div>
          <div v-else class="setting-card-scroll">
            <template v-if="agentOptions.length">
              <p class="setting-card-section-label">智能体</p>
              <div class="setting-card-list">
                <button
                  v-for="opt in agentOptions"
                  :key="`agent-${opt.id}`"
                  type="button"
                  class="setting-card-item"
                  role="menuitem"
                  :disabled="generating"
                  @click.stop="pickAgent(opt)"
                >
                  <div class="setting-card-thumb setting-card-thumb--agent" aria-hidden="true">
                    <ShimmerImage
                      v-if="opt.thumbnail"
                      :src="opt.thumbnail"
                      :alt="opt.name"
                      img-class="setting-card-thumb__img"
                      wrapper-class="setting-card-thumb__shimmer"
                      object-fit="cover"
                      reveal-direction="fade"
                      :min-shimmer-ms="280"
                    />
                    <span v-else class="setting-card-thumb__letter">{{ (opt.name || '?').slice(0, 1) }}</span>
                  </div>
                  <div class="setting-card-body">
                    <div class="setting-card-title-row">
                      <span class="setting-card-title">{{ opt.name }}</span>
                      <span class="setting-card-tag">智能体</span>
                    </div>
                    <p v-if="opt.desc" class="setting-card-desc">{{ opt.desc }}</p>
                  </div>
                </button>
              </div>
            </template>

            <div v-else class="setting-card-empty">暂无可用智能体</div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick, onMounted, onUnmounted, computed } from 'vue'
import ShimmerImage from '~/components/common/ShimmerImage.vue'
import type { AgentOption } from './AgentPickerModal.vue'
import { aidAgentList } from '~/utils/businessApi'
import { useCreationStore } from '~/stores/creation'
import { buildAidAgentListScopeParams } from '~/utils/createFlowProjectContext'
import {
  CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY,
  agentOptionsFromGroup
} from '~/utils/extractAgentBiz'

const creationStore = useCreationStore()

const emit = defineEmits<{
  select: [payload: { agentCode?: string; imageIndex: number }]
}>()

const props = withDefaults(
  defineProps<{
    imageIndex: number
    isSupported: boolean
    isWhiteBaseReady: boolean
    disabled?: boolean
    generating?: boolean
  }>(),
  {
    imageIndex: 0,
    isSupported: false,
    isWhiteBaseReady: false,
    disabled: false,
    generating: false
  }
)

const ESTIMATED_PANEL_MIN = 220
const GAP = 8

const rootRef = ref<HTMLElement | null>(null)
const triggerRef = ref<HTMLElement | null>(null)
const panelRef = ref<HTMLElement | null>(null)
const open = ref(false)
const openUpward = ref(false)
const readyToShowPanel = ref(false)
const panelFixedStyle = ref<Record<string, string>>({})

const loading = ref(false)
const agentOptions = ref<AgentOption[]>([])

const panelStyle = computed(() => panelFixedStyle.value)

async function loadOptions() {
  loading.value = true
  try {
    const groups = await aidAgentList({
      bizCategoryCodes: [CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY],
      ...buildAidAgentListScopeParams(creationStore)
    })
    agentOptions.value = agentOptionsFromGroup(groups, CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY)
  } catch {
    agentOptions.value = []
  } finally {
    loading.value = false
  }
}

function pickAgent(opt: AgentOption) {
  if (props.generating) return
  const agentCode = String(opt?.id || '').trim()
  if (!agentCode) return
  emit('select', { agentCode, imageIndex: props.imageIndex })
  open.value = false
}

function updatePlacement() {
  if (!open.value || !triggerRef.value) return

  const rect = triggerRef.value.getBoundingClientRect()
  const spaceBelow = window.innerHeight - rect.bottom - GAP
  const spaceAbove = rect.top - GAP

  let upward = false
  if (spaceBelow >= ESTIMATED_PANEL_MIN) {
    upward = false
  } else if (spaceAbove >= ESTIMATED_PANEL_MIN) {
    upward = true
  } else {
    upward = spaceAbove > spaceBelow
  }

  openUpward.value = upward

  const minW = 320
  const widthPx = Math.min(Math.max(rect.width, minW), Math.min(420, window.innerWidth - 24))
  let leftPx = rect.left
  leftPx = Math.max(12, Math.min(leftPx, window.innerWidth - widthPx - 12))

  const z = '5500'

  if (!upward) {
    panelFixedStyle.value = {
      position: 'fixed',
      left: `${leftPx}px`,
      top: `${rect.bottom + GAP}px`,
      width: `${widthPx}px`,
      zIndex: z
    }
  } else {
    panelFixedStyle.value = {
      position: 'fixed',
      left: `${leftPx}px`,
      bottom: `${window.innerHeight - rect.top + GAP}px`,
      width: `${widthPx}px`,
      zIndex: z
    }
  }
}

function toggle() {
  if (props.disabled) return
  open.value = !open.value
}

function onViewportChange() {
  if (open.value) updatePlacement()
}

let docMouseDownHandler: ((e: MouseEvent) => void) | null = null

function unbindClickOutside() {
  if (docMouseDownHandler) {
    document.removeEventListener('mousedown', docMouseDownHandler, true)
    docMouseDownHandler = null
  }
}

function bindClickOutside() {
  unbindClickOutside()
  docMouseDownHandler = (e: MouseEvent) => {
    const root = rootRef.value
    const panel = panelRef.value
    if (!open.value || !root) return
    const target = e.target as Node | null
    if (!target) return
    if (root.contains(target) || (panel && panel.contains(target))) return
    open.value = false
  }
  document.addEventListener('mousedown', docMouseDownHandler, true)
}

watch(
  () => open.value,
  async (isOpen) => {
    if (isOpen) {
      readyToShowPanel.value = false
      unbindClickOutside()
      if (props.isSupported && props.isWhiteBaseReady) {
        void loadOptions()
      }
      await nextTick()
      updatePlacement()
      readyToShowPanel.value = true
      await nextTick()
      bindClickOutside()
    } else {
      readyToShowPanel.value = false
      panelFixedStyle.value = {}
      unbindClickOutside()
    }
  },
  { flush: 'post' }
)

watch(
  () => props.imageIndex,
  () => {
    if (open.value) updatePlacement()
  }
)

onMounted(() => {
  window.addEventListener('resize', onViewportChange)
  window.addEventListener('scroll', onViewportChange, true)
})

onUnmounted(() => {
  unbindClickOutside()
  window.removeEventListener('resize', onViewportChange)
  window.removeEventListener('scroll', onViewportChange, true)
})
</script>

<style scoped>
.setting-card-popover-root {
  display: inline-flex;
  vertical-align: middle;
}

.setting-card-popover-trigger {
  display: inline-flex;
}

.setting-card-popover-trigger.is-disabled {
  cursor: not-allowed;
}

.setting-card-panel {
  display: flex;
  flex-direction: column;
  padding: 8px 10px;
  border-radius: 12px;
  background: rgba(19, 23, 34, 0.98);
  border: 1px solid rgba(74, 231, 253, 0.22);
  box-shadow: 0 12px 36px rgba(0, 0, 0, 0.45);
  box-sizing: border-box;
  max-height: min(420px, 62vh);
  overflow: hidden;
}

.setting-card-panel.is-open-down {
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
}

.setting-card-panel.is-open-up {
  border-bottom-left-radius: 10px;
  border-bottom-right-radius: 10px;
}

.setting-card-alert {
  flex-shrink: 0;
  margin-bottom: 0;
}

.setting-card-scroll {
  display: flex;
  flex-direction: column;
  min-height: 0;
  overflow-x: hidden;
  overflow-y: auto;
  margin: 0 -2px;
  padding: 0 2px 2px;
  scrollbar-width: thin;
  scrollbar-color: rgba(120, 140, 170, 0.4) transparent;
}

.setting-card-scroll::-webkit-scrollbar {
  width: 4px;
}

.setting-card-scroll::-webkit-scrollbar-thumb {
  background: rgba(120, 140, 170, 0.35);
  border-radius: 4px;
}

.setting-card-section-label {
  flex-shrink: 0;
  margin: 6px 0 4px;
  padding: 0 2px;
  font-size: 12px;
  font-weight: 600;
  color: #8e97a5;
}

.setting-card-section-label:first-of-type {
  margin-top: 0;
}

.setting-card-list {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.setting-card-empty {
  padding: 12px 8px;
  font-size: 13px;
  color: #8e97a5;
  text-align: center;
}

.setting-card-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  width: 100%;
  padding: 8px;
  margin: 0;
  border: none;
  border-radius: 8px;
  background: transparent;
  cursor: pointer;
  text-align: left;
  color: #e8ecf4;
  transition: background 0.15s ease;
  box-sizing: border-box;
}

.setting-card-item:hover:not(:disabled) {
  background: rgba(74, 231, 253, 0.08);
}

.setting-card-item:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.setting-card-thumb {
  position: relative;
  flex-shrink: 0;
  width: 44px;
  height: 44px;
  border-radius: 8px;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #1a2233;
}

.setting-card-thumb--agent {
  background: linear-gradient(135deg, #2a3550 0%, #3d4a68 100%);
}

.setting-card-thumb__shimmer {
  width: 100%;
  height: 100%;
}

.setting-card-thumb :deep(.setting-card-thumb__shimmer) {
  width: 100%;
  height: 100%;
}

.setting-card-thumb__img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.setting-card-thumb__letter {
  line-height: 1;
  font-weight: 600;
}

.setting-card-body {
  flex: 1;
  min-width: 0;
}

.setting-card-title-row {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 4px 8px;
  font-size: 14px;
  font-weight: 600;
  line-height: 1.35;
}

.setting-card-title {
  color: #f1f5ff;
}

.setting-card-tag {
  font-size: 12px;
  font-weight: 500;
  color: #a8b4c8;
}

.setting-card-desc {
  margin: 4px 0 0;
  font-size: 12px;
  line-height: 1.4;
  color: #8e97a5;
}

.setting-card-fade-enter-active,
.setting-card-fade-leave-active {
  transition: opacity 0.15s ease, transform 0.15s ease;
}

.setting-card-fade-enter-from,
.setting-card-fade-leave-to {
  opacity: 0;
  transform: translateY(4px);
}

.setting-card-panel.is-open-up.setting-card-fade-enter-from,
.setting-card-panel.is-open-up.setting-card-fade-leave-to {
  transform: translateY(-4px);
}
</style>

// components/steps/SettingCardImagePopover.tsx
'use client'

import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { Alert } from 'antd'
import { ShimmerImage } from '~/components/common/ShimmerImage'
import type { AgentOption } from '~/types/modelAgentOptions'
import { aidAgentList } from '~/utils/businessApi'
import { useCreationStore } from '~/stores/creation'
import { buildAidAgentListScopeParams } from '~/utils/createFlowProjectContext'
import {
  CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY,
  agentOptionsFromGroup
} from '~/utils/extractAgentBiz'
import './SettingCardImagePopover.css'

interface Props {
  imageIndex?: number
  isSupported?: boolean
  isWhiteBaseReady?: boolean
  disabled?: boolean
  generating?: boolean
  onSelect?: (payload: { agentCode?: string; imageIndex: number }) => void
  /** 原默认插槽：触发区内容 */
  children?: ReactNode
}

const ESTIMATED_PANEL_MIN = 220
const GAP = 8

/** 原 <Transition name="setting-card-fade"> 时长（transition: opacity/transform 0.15s ease） */
const FADE_DURATION_MS = 150

/** 对齐 Vue transition 的 nextFrame：两帧后再切换 class 才能触发过渡 */
function nextFrame(cb: () => void) {
  requestAnimationFrame(() => {
    requestAnimationFrame(cb)
  })
}

export function SettingCardImagePopover({
  imageIndex = 0,
  isSupported = false,
  isWhiteBaseReady = false,
  disabled = false,
  generating = false,
  onSelect,
  children
}: Props) {
  const rootRef = useRef<HTMLDivElement | null>(null)
  const triggerRef = useRef<HTMLDivElement | null>(null)
  const panelRef = useRef<HTMLDivElement | null>(null)
  const [open, setOpen] = useState(false)
  const [openUpward, setOpenUpward] = useState(false)
  const [readyToShowPanel, setReadyToShowPanel] = useState(false)
  const [panelFixedStyle, setPanelFixedStyle] = useState<Record<string, string>>({})

  const [loading, setLoading] = useState(false)
  const [agentOptions, setAgentOptions] = useState<AgentOption[]>([])

  // 事件回调（resize/scroll/click-outside）读取当前展开态用
  const openRef = useRef(false)
  const docMouseDownHandlerRef = useRef<((e: MouseEvent) => void) | null>(null)

  // rendered 控制 DOM 存在（含离场动画期间），transitionClass 复刻 Vue transition 各阶段 class
  const [rendered, setRendered] = useState(false)
  const [transitionClass, setTransitionClass] = useState('')
  const renderedRef = useRef(false)
  const transitionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const panelStyle = panelFixedStyle as CSSProperties

  function setOpenBoth(value: boolean) {
    openRef.current = value
    setOpen(value)
  }

  async function loadOptions() {
    setLoading(true)
    try {
      const groups = await aidAgentList({
        bizCategoryCodes: [CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY],
        ...buildAidAgentListScopeParams(useCreationStore.getState())
      })
      setAgentOptions(agentOptionsFromGroup(groups, CHARACTER_CARD_IMAGE_AGENT_BIZ_CATEGORY))
    } catch {
      setAgentOptions([])
    } finally {
      setLoading(false)
    }
  }

  function pickAgent(opt: AgentOption) {
    if (generating) return
    const agentCode = String(opt?.id || '').trim()
    if (!agentCode) return
    onSelect?.({ agentCode, imageIndex })
    setOpenBoth(false)
  }

  function updatePlacement() {
    if (!openRef.current || !triggerRef.current) return

    const rect = triggerRef.current.getBoundingClientRect()
    const spaceBelow = window.innerHeight - rect.bottom - GAP
    const spaceAbove = rect.top - GAP

    let upward = false
    if (spaceBelow >= ESTIMATED_PANEL_MIN) {
      upward = false
    } else if (spaceAbove >= ESTIMATED_PANEL_MIN) {
      upward = true
    } else {
      upward = spaceAbove > spaceBelow
    }

    setOpenUpward(upward)

    const minW = 320
    const widthPx = Math.min(Math.max(rect.width, minW), Math.min(420, window.innerWidth - 24))
    let leftPx = rect.left
    leftPx = Math.max(12, Math.min(leftPx, window.innerWidth - widthPx - 12))

    const z = '5500'

    if (!upward) {
      setPanelFixedStyle({
        position: 'fixed',
        left: `${leftPx}px`,
        top: `${rect.bottom + GAP}px`,
        width: `${widthPx}px`,
        zIndex: z
      })
    } else {
      setPanelFixedStyle({
        position: 'fixed',
        left: `${leftPx}px`,
        bottom: `${window.innerHeight - rect.top + GAP}px`,
        width: `${widthPx}px`,
        zIndex: z
      })
    }
  }

  function toggle() {
    if (disabled) return
    setOpenBoth(!openRef.current)
  }

  function unbindClickOutside() {
    if (docMouseDownHandlerRef.current) {
      document.removeEventListener('mousedown', docMouseDownHandlerRef.current, true)
      docMouseDownHandlerRef.current = null
    }
  }

  function bindClickOutside() {
    unbindClickOutside()
    docMouseDownHandlerRef.current = (e: MouseEvent) => {
      const root = rootRef.current
      const panel = panelRef.current
      if (!openRef.current || !root) return
      const target = e.target as Node | null
      if (!target) return
      if (root.contains(target) || (panel && panel.contains(target))) return
      setOpenBoth(false)
    }
    document.addEventListener('mousedown', docMouseDownHandlerRef.current, true)
  }

  // 原 watch(() => open.value, ..., { flush: 'post' })
  useEffect(() => {
    if (open) {
      setReadyToShowPanel(false)
      unbindClickOutside()
      if (isSupported && isWhiteBaseReady) {
        void loadOptions()
      }
      let cancelled = false
      // 原 await nextTick()：等触发区渲染稳定后再计算方向
      requestAnimationFrame(() => {
        if (cancelled) return
        updatePlacement()
        setReadyToShowPanel(true)
        // 原第二个 await nextTick()：面板挂载后再绑定 click-outside
        requestAnimationFrame(() => {
          if (cancelled) return
          bindClickOutside()
        })
      })
      return () => {
        cancelled = true
      }
    }
    setReadyToShowPanel(false)
    unbindClickOutside()
    return undefined
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // 原 watch(() => props.imageIndex)：展开时索引变化需重算定位
  useEffect(() => {
    if (openRef.current) updatePlacement()
     
  }, [imageIndex])

  // 复刻 <Transition name="setting-card-fade">：进入/离开动画 class + 离场后再卸载
  const visible = open && readyToShowPanel
  useEffect(() => {
    if (transitionTimerRef.current) {
      clearTimeout(transitionTimerRef.current)
      transitionTimerRef.current = null
    }

    if (visible) {
      renderedRef.current = true
      setRendered(true)
      setTransitionClass('setting-card-fade-enter-from setting-card-fade-enter-active')
      nextFrame(() => {
        setTransitionClass('setting-card-fade-enter-active')
        transitionTimerRef.current = setTimeout(() => {
          transitionTimerRef.current = null
          setTransitionClass('')
        }, FADE_DURATION_MS)
      })
      return
    }

    if (!renderedRef.current) return
    setTransitionClass('setting-card-fade-leave-active setting-card-fade-leave-to')
    transitionTimerRef.current = setTimeout(() => {
      transitionTimerRef.current = null
      renderedRef.current = false
      setRendered(false)
      setTransitionClass('')
      // 离场结束后再复位方向与定位（Vue 在关闭瞬间清空，React 侧保留至卸载避免离场闪跳）
      setOpenUpward(false)
      setPanelFixedStyle({})
    }, FADE_DURATION_MS)
  }, [visible])

  useEffect(() => {
    const onViewportChange = () => {
      if (openRef.current) updatePlacement()
    }
    window.addEventListener('resize', onViewportChange)
    window.addEventListener('scroll', onViewportChange, true)
    return () => {
      unbindClickOutside()
      window.removeEventListener('resize', onViewportChange)
      window.removeEventListener('scroll', onViewportChange, true)
      if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current)
    }
     
  }, [])

  const panelClass = [
    'setting-card-panel',
    !openUpward ? 'is-open-down' : 'is-open-up',
    transitionClass
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div ref={rootRef} className="setting-card-popover-root">
      <div
        ref={triggerRef}
        className={
          disabled ? 'setting-card-popover-trigger is-disabled' : 'setting-card-popover-trigger'
        }
        onClick={(e) => {
          e.stopPropagation()
          toggle()
        }}
      >
        {children}
      </div>

      {rendered && typeof document !== 'undefined'
        ? createPortal(
            <div
              ref={panelRef}
              className={panelClass}
              style={panelStyle}
              role="menu"
              aria-label="生成角色设定卡"
            >
              {!isSupported ? (
                <Alert
                  type="info"
                  showIcon
                  message="仅支持角色形态"
                  className="setting-card-alert"
                />
              ) : !isWhiteBaseReady ? (
                <Alert
                  type="warning"
                  showIcon
                  message="请先选择平台生成或本地上传的角色图"
                  className="setting-card-alert"
                />
              ) : loading ? (
                <div className="setting-card-empty">加载中…</div>
              ) : (
                <div className="setting-card-scroll">
                  {agentOptions.length ? (
                    <>
                      <p className="setting-card-section-label">智能体</p>
                      <div className="setting-card-list">
                        {agentOptions.map((opt) => (
                          <button
                            key={`agent-${opt.id}`}
                            type="button"
                            className="setting-card-item"
                            role="menuitem"
                            disabled={generating}
                            onClick={(e) => {
                              e.stopPropagation()
                              pickAgent(opt)
                            }}
                          >
                            <div
                              className="setting-card-thumb setting-card-thumb--agent"
                              aria-hidden="true"
                            >
                              {opt.thumbnail ? (
                                <ShimmerImage
                                  src={opt.thumbnail}
                                  alt={opt.name}
                                  imgClass="setting-card-thumb__img"
                                  wrapperClass="setting-card-thumb__shimmer"
                                  objectFit="cover"
                                  revealDirection="fade"
                                  minShimmerMs={280}
                                />
                              ) : (
                                <span className="setting-card-thumb__letter">
                                  {(opt.name || '?').slice(0, 1)}
                                </span>
                              )}
                            </div>
                            <div className="setting-card-body">
                              <div className="setting-card-title-row">
                                <span className="setting-card-title">{opt.name}</span>
                                <span className="setting-card-tag">智能体</span>
                              </div>
                              {opt.desc ? <p className="setting-card-desc">{opt.desc}</p> : null}
                            </div>
                          </button>
                        ))}
                      </div>
                    </>
                  ) : (
                    <div className="setting-card-empty">暂无可用智能体</div>
                  )}
                </div>
              )}
            </div>,
            document.body
          )
        : null}
    </div>
  )
}

export default SettingCardImagePopover
