// components/steps/UpscaleModelPopover.vue
<template>
  <div ref="rootRef" class="upscale-model-popover-root">
    <div
      ref="triggerRef"
      class="upscale-model-popover-trigger"
      :class="{ 'is-disabled': disabled }"
      @click.stop="toggle"
    >
      <slot />
    </div>

    <Teleport to="body">
      <Transition name="upscale-model-fade">
        <div
          v-if="open && readyToShowPanel"
          ref="panelRef"
          class="upscale-model-panel"
          :class="{ 'is-open-down': !openUpward, 'is-open-up': openUpward }"
          :style="panelStyle"
          role="menu"
          aria-label="变清晰模型"
        >
          <div v-if="loading" class="upscale-model-empty">加载中…</div>
          <template v-else-if="modelOptions.length">
            <div class="upscale-model-list">
              <button
                v-for="opt in modelOptions"
                :key="`upscale-${opt.id}`"
                type="button"
                class="upscale-model-item"
                role="menuitem"
                :disabled="generating"
                @click.stop="pick(opt)"
              >
                <div class="upscale-model-thumb" aria-hidden="true">
                  <img
                    v-if="opt.icon"
                    :src="opt.icon"
                    :alt="opt.name"
                    class="upscale-model-thumb__img"
                  />
                  <span v-else class="upscale-model-thumb__letter">{{
                    (opt.name || '?').slice(0, 1)
                  }}</span>
                </div>
                <div class="upscale-model-body">
                  <div class="upscale-model-title-row">
                    <span class="upscale-model-title">{{ opt.name }}</span>
                    <span v-if="opt.resolutionLabel" class="upscale-model-tag">{{
                      opt.resolutionLabel
                    }}</span>
                  </div>
                  <p v-if="opt.desc" class="upscale-model-desc">{{ opt.desc }}</p>
                </div>
              </button>
            </div>
          </template>
          <div v-else class="upscale-model-empty">暂无可用高清模型</div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick, onMounted, onUnmounted, computed } from 'vue'
import { userModelListByFuncCodes } from '~/utils/businessApi'
import { AI_MODEL_FUNC_CODE } from '~/utils/aiModelFuncCodes'
import { modelsFromListByFuncGroups } from '~/utils/modelListByFuncBatch'
import { resolveUpscaleResolutionFromModel } from '~/utils/modelCapability'
import type { UserModelListItem } from '~/types/business-api'

export interface UpscaleModelOption {
  id: string
  name: string
  icon?: string
  iconBg?: string
  desc?: string
  resolution: string
  resolutionLabel?: string
}

const emit = defineEmits<{
  select: [payload: { modelCode: string; resolution: string; imageIndex: number }]
}>()

const props = withDefaults(
  defineProps<{
    imageIndex: number
    disabled?: boolean
    generating?: boolean
    /** form-image 用小写 2k；分镜图高清用大写 2K */
    resolutionFormat?: 'lower' | 'upper'
    /** 父级批量 listByFunc 预取的高清模型池（funcCode=image_upscale） */
    prefetchedModels?: UserModelListItem[] | null
  }>(),
  {
    imageIndex: 0,
    disabled: false,
    generating: false,
    resolutionFormat: 'lower',
    prefetchedModels: null
  }
)

const ESTIMATED_PANEL_MIN = 200
const GAP = 8

const rootRef = ref<HTMLElement | null>(null)
const triggerRef = ref<HTMLElement | null>(null)
const panelRef = ref<HTMLElement | null>(null)
const open = ref(false)
const openUpward = ref(false)
const readyToShowPanel = ref(false)
const panelFixedStyle = ref<Record<string, string>>({})
const loading = ref(false)
const modelOptions = ref<UpscaleModelOption[]>([])

const panelStyle = computed(() => panelFixedStyle.value)

function normalizeSizeCode(raw: string): string {
  const t = String(raw || '').trim()
  if (!t) return ''
  if (/^\d+k$/i.test(t)) return t.toLowerCase()
  return t.toLowerCase()
}

function formatResolutionLabel(raw: string): string {
  const normalized = normalizeSizeCode(raw) || '2k'
  return /^\d+k$/i.test(normalized) ? normalized.toUpperCase() : normalized
}

function mapModelRow(item: UserModelListItem): UpscaleModelOption | null {
  const code = String(item.modelCode || '').trim()
  if (!code) return null
  const resolution = resolveUpscaleResolutionFromModel(item, props.resolutionFormat)
  const rawSize = String(
    item.defaultSizeCode ||
      (item.capability as { defaultSize?: string } | null | undefined)?.defaultSize ||
      resolution
  ).trim()
  return {
    id: code,
    name: item.modelName || code,
    icon: String(item.providerLogo || '').trim() || undefined,
    iconBg: '#60A5FA',
    desc: item.providerName ? `服务商：${item.providerName}` : '',
    resolution,
    resolutionLabel: formatResolutionLabel(rawSize || resolution)
  }
}

function applyModelRows(models: UserModelListItem[]) {
  modelOptions.value = (Array.isArray(models) ? models : [])
    .map(mapModelRow)
    .filter((m): m is UpscaleModelOption => Boolean(m))
}

async function loadOptions() {
  const prefetched = props.prefetchedModels
  if (Array.isArray(prefetched) && prefetched.length > 0) {
    applyModelRows(prefetched)
    return
  }

  loading.value = true
  try {
    const groups = await userModelListByFuncCodes([AI_MODEL_FUNC_CODE.IMAGE_UPSCALE])
    const models = modelsFromListByFuncGroups(groups, AI_MODEL_FUNC_CODE.IMAGE_UPSCALE)
    applyModelRows(models)
  } catch {
    modelOptions.value = []
  } finally {
    loading.value = false
  }
}

function pick(opt: UpscaleModelOption) {
  if (props.generating) return
  const modelCode = String(opt.id || '').trim()
  if (!modelCode) return
  emit('select', {
    modelCode,
    resolution: opt.resolution,
    imageIndex: props.imageIndex
  })
  open.value = false
}

function updatePlacement() {
  if (!open.value || !triggerRef.value) return

  const rect = triggerRef.value.getBoundingClientRect()
  const spaceBelow = window.innerHeight - rect.bottom - GAP
  const spaceAbove = rect.top - GAP

  let upward = false
  if (spaceBelow >= ESTIMATED_PANEL_MIN) {
    upward = false
  } else if (spaceAbove >= ESTIMATED_PANEL_MIN) {
    upward = true
  } else {
    upward = spaceAbove > spaceBelow
  }

  openUpward.value = upward

  const minW = 320
  const widthPx = Math.min(Math.max(rect.width, minW), Math.min(420, window.innerWidth - 24))
  let leftPx = rect.left
  leftPx = Math.max(12, Math.min(leftPx, window.innerWidth - widthPx - 12))

  const z = '5500'

  if (!upward) {
    panelFixedStyle.value = {
      position: 'fixed',
      left: `${leftPx}px`,
      top: `${rect.bottom + GAP}px`,
      width: `${widthPx}px`,
      zIndex: z
    }
  } else {
    panelFixedStyle.value = {
      position: 'fixed',
      left: `${leftPx}px`,
      bottom: `${window.innerHeight - rect.top + GAP}px`,
      width: `${widthPx}px`,
      zIndex: z
    }
  }
}

function toggle() {
  if (props.disabled) return
  open.value = !open.value
}

function onViewportChange() {
  if (open.value) updatePlacement()
}

let docMouseDownHandler: ((e: MouseEvent) => void) | null = null

function unbindClickOutside() {
  if (docMouseDownHandler) {
    document.removeEventListener('mousedown', docMouseDownHandler, true)
    docMouseDownHandler = null
  }
}

function bindClickOutside() {
  unbindClickOutside()
  docMouseDownHandler = (e: MouseEvent) => {
    const root = rootRef.value
    const panel = panelRef.value
    if (!open.value || !root) return
    const target = e.target as Node | null
    if (!target) return
    if (root.contains(target) || (panel && panel.contains(target))) return
    open.value = false
  }
  document.addEventListener('mousedown', docMouseDownHandler, true)
}

watch(
  () => props.prefetchedModels,
  () => {
    if (open.value) void loadOptions()
  },
  { deep: true }
)

watch(
  () => open.value,
  async (isOpen) => {
    if (isOpen) {
      readyToShowPanel.value = false
      unbindClickOutside()
      void loadOptions()
      await nextTick()
      updatePlacement()
      readyToShowPanel.value = true
      await nextTick()
      bindClickOutside()
    } else {
      readyToShowPanel.value = false
      panelFixedStyle.value = {}
      unbindClickOutside()
    }
  },
  { flush: 'post' }
)

watch(
  () => props.imageIndex,
  () => {
    if (open.value) updatePlacement()
  }
)

onMounted(() => {
  window.addEventListener('resize', onViewportChange)
  window.addEventListener('scroll', onViewportChange, true)
})

onUnmounted(() => {
  unbindClickOutside()
  window.removeEventListener('resize', onViewportChange)
  window.removeEventListener('scroll', onViewportChange, true)
})
</script>

<style scoped>
.upscale-model-popover-root {
  display: inline-flex;
  vertical-align: middle;
}

.upscale-model-popover-trigger {
  display: inline-flex;
}

.upscale-model-popover-trigger.is-disabled {
  cursor: not-allowed;
}

.upscale-model-panel {
  display: flex;
  flex-direction: column;
  padding: 8px 10px;
  border-radius: 12px;
  background: rgba(19, 23, 34, 0.98);
  border: 1px solid rgba(74, 231, 253, 0.22);
  box-shadow: 0 12px 36px rgba(0, 0, 0, 0.45);
  box-sizing: border-box;
  max-height: min(420px, 62vh);
  overflow: hidden;
}

.upscale-model-panel.is-open-down {
  border-top-left-radius: 10px;
  border-top-right-radius: 10px;
}

.upscale-model-panel.is-open-up {
  border-bottom-left-radius: 10px;
  border-bottom-right-radius: 10px;
}
.upscale-model-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-height: 0;
  overflow-x: hidden;
  overflow-y: auto;
  margin: 0 -2px;
  padding: 0 2px 2px;
  scrollbar-width: thin;
  scrollbar-color: rgba(120, 140, 170, 0.4) transparent;
}

.upscale-model-list::-webkit-scrollbar {
  width: 4px;
}

.upscale-model-list::-webkit-scrollbar-thumb {
  background: rgba(120, 140, 170, 0.35);
  border-radius: 4px;
}

.upscale-model-empty {
  padding: 12px 8px;
  font-size: 13px;
  color: #8e97a5;
  text-align: center;
}

.upscale-model-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  width: 100%;
  padding: 8px;
  margin: 0;
  border: none;
  border-radius: 8px;
  background: transparent;
  cursor: pointer;
  text-align: left;
  color: #e8ecf4;
  transition: background 0.15s ease;
  box-sizing: border-box;
}

.upscale-model-item:hover:not(:disabled) {
  background: rgba(74, 231, 253, 0.08);
}

.upscale-model-item:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.upscale-model-thumb {
  flex-shrink: 0;
  width: 22px;
  height: 22px;
  border-radius: 8px;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 14px;
  background: rgba(6, 10, 18, 0.55);
  font-weight: 600;
}

.upscale-model-thumb__img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.upscale-model-thumb__letter {
  line-height: 1;
}

.upscale-model-body {
  flex: 1;
  min-width: 0;
}

.upscale-model-title-row {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 4px 8px;
  font-size: 14px;
  font-weight: 600;
  line-height: 1.35;
}

.upscale-model-title {
  color: #f1f5ff;
}

.upscale-model-tag {
  font-size: 12px;
  font-weight: 500;
  color: #4ae7fd;
}

.upscale-model-desc {
  margin: 4px 0 0;
  font-size: 12px;
  line-height: 1.4;
  color: #8e97a5;
}

.upscale-model-fade-enter-active,
.upscale-model-fade-leave-active {
  transition:
    opacity 0.15s ease,
    transform 0.15s ease;
}

.upscale-model-fade-enter-from,
.upscale-model-fade-leave-to {
  opacity: 0;
  transform: translateY(4px);
}

.upscale-model-panel.is-open-up.upscale-model-fade-enter-from,
.upscale-model-panel.is-open-up.upscale-model-fade-leave-to {
  transform: translateY(-4px);
}
</style>

// components/steps/UpscaleModelPopover.tsx
'use client'

import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { userModelListByFuncCodes } from '~/utils/businessApi'
import { AI_MODEL_FUNC_CODE } from '~/utils/aiModelFuncCodes'
import { modelsFromListByFuncGroups } from '~/utils/modelListByFuncBatch'
import { resolveUpscaleResolutionFromModel } from '~/utils/modelCapability'
import { shouldShowModelFreeBadge } from '~/utils/modelFreeStatus'
import type { UserModelListItem } from '~/types/business-api'
import { ModelFreeBadge } from '~/components/common/ModelFreeBadge'
import './UpscaleModelPopover.css'

export interface UpscaleModelOption {
  id: string
  name: string
  icon?: string
  iconBg?: string
  desc?: string
  resolution: string
  resolutionLabel?: string
  isFree?: boolean
}

interface Props {
  imageIndex?: number
  disabled?: boolean
  generating?: boolean
  /** form-image 用小写 2k；分镜图高清用大写 2K */
  resolutionFormat?: 'lower' | 'upper'
  /** 父级批量 listByFunc 预取的高清模型池（funcCode=image_upscale） */
  prefetchedModels?: UserModelListItem[] | null
  onSelect?: (payload: { modelCode: string; resolution: string; imageIndex: number }) => void
  /** 原默认插槽：触发区内容 */
  children?: ReactNode
}

const ESTIMATED_PANEL_MIN = 200
const GAP = 8

/** 原 <Transition name="upscale-model-fade"> 时长（transition: opacity/transform 0.15s ease） */
const FADE_DURATION_MS = 150

/** 对齐 Vue transition 的 nextFrame：两帧后再切换 class 才能触发过渡 */
function nextFrame(cb: () => void) {
  requestAnimationFrame(() => {
    requestAnimationFrame(cb)
  })
}

function normalizeSizeCode(raw: string): string {
  const t = String(raw || '').trim()
  if (!t) return ''
  if (/^\d+k$/i.test(t)) return t.toLowerCase()
  return t.toLowerCase()
}

function formatResolutionLabel(raw: string): string {
  const normalized = normalizeSizeCode(raw) || '2k'
  return /^\d+k$/i.test(normalized) ? normalized.toUpperCase() : normalized
}

export function UpscaleModelPopover({
  imageIndex = 0,
  disabled = false,
  generating = false,
  resolutionFormat = 'lower',
  prefetchedModels = null,
  onSelect,
  children
}: Props) {
  const rootRef = useRef<HTMLDivElement | null>(null)
  const triggerRef = useRef<HTMLDivElement | null>(null)
  const panelRef = useRef<HTMLDivElement | null>(null)
  const [open, setOpen] = useState(false)
  const [openUpward, setOpenUpward] = useState(false)
  const [readyToShowPanel, setReadyToShowPanel] = useState(false)
  const [panelFixedStyle, setPanelFixedStyle] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(false)
  const [modelOptions, setModelOptions] = useState<UpscaleModelOption[]>([])

  // 事件回调（resize/scroll/click-outside）读取当前展开态用
  const openRef = useRef(false)
  const docMouseDownHandlerRef = useRef<((e: MouseEvent) => void) | null>(null)

  // rendered 控制 DOM 存在（含离场动画期间），transitionClass 复刻 Vue transition 各阶段 class
  const [rendered, setRendered] = useState(false)
  const [transitionClass, setTransitionClass] = useState('')
  const renderedRef = useRef(false)
  const transitionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const panelStyle = panelFixedStyle as CSSProperties

  function setOpenBoth(value: boolean) {
    openRef.current = value
    setOpen(value)
  }

  function mapModelRow(item: UserModelListItem): UpscaleModelOption | null {
    const code = String(item.modelCode || '').trim()
    if (!code) return null
    const resolution = resolveUpscaleResolutionFromModel(item, resolutionFormat)
    const rawSize = String(
      item.defaultSizeCode ||
        (item.capability as { defaultSize?: string } | null | undefined)?.defaultSize ||
        resolution
    ).trim()
    return {
      id: code,
      name: item.modelName || code,
      icon: String(item.providerLogo || '').trim() || undefined,
      iconBg: '#60A5FA',
      desc: item.providerName ? `服务商：${item.providerName}` : '',
      resolution,
      resolutionLabel: formatResolutionLabel(rawSize || resolution),
      isFree: item.isFree === true
    }
  }

  function applyModelRows(models: UserModelListItem[]) {
    setModelOptions(
      (Array.isArray(models) ? models : [])
        .map(mapModelRow)
        .filter((m): m is UpscaleModelOption => Boolean(m))
    )
  }

  async function loadOptions() {
    const prefetched = prefetchedModels
    if (Array.isArray(prefetched) && prefetched.length > 0) {
      applyModelRows(prefetched)
      return
    }

    setLoading(true)
    try {
      const groups = await userModelListByFuncCodes([AI_MODEL_FUNC_CODE.IMAGE_UPSCALE])
      const models = modelsFromListByFuncGroups(groups, AI_MODEL_FUNC_CODE.IMAGE_UPSCALE)
      applyModelRows(models)
    } catch {
      setModelOptions([])
    } finally {
      setLoading(false)
    }
  }

  function pick(opt: UpscaleModelOption) {
    if (generating) return
    const modelCode = String(opt.id || '').trim()
    if (!modelCode) return
    onSelect?.({
      modelCode,
      resolution: opt.resolution,
      imageIndex
    })
    setOpenBoth(false)
  }

  function updatePlacement() {
    if (!openRef.current || !triggerRef.current) return

    const rect = triggerRef.current.getBoundingClientRect()
    const spaceBelow = window.innerHeight - rect.bottom - GAP
    const spaceAbove = rect.top - GAP

    let upward = false
    if (spaceBelow >= ESTIMATED_PANEL_MIN) {
      upward = false
    } else if (spaceAbove >= ESTIMATED_PANEL_MIN) {
      upward = true
    } else {
      upward = spaceAbove > spaceBelow
    }

    setOpenUpward(upward)

    const minW = 320
    const widthPx = Math.min(Math.max(rect.width, minW), Math.min(420, window.innerWidth - 24))
    let leftPx = rect.left
    leftPx = Math.max(12, Math.min(leftPx, window.innerWidth - widthPx - 12))

    const z = '5500'

    if (!upward) {
      setPanelFixedStyle({
        position: 'fixed',
        left: `${leftPx}px`,
        top: `${rect.bottom + GAP}px`,
        width: `${widthPx}px`,
        zIndex: z
      })
    } else {
      setPanelFixedStyle({
        position: 'fixed',
        left: `${leftPx}px`,
        bottom: `${window.innerHeight - rect.top + GAP}px`,
        width: `${widthPx}px`,
        zIndex: z
      })
    }
  }

  function toggle() {
    if (disabled) return
    setOpenBoth(!openRef.current)
  }

  function unbindClickOutside() {
    if (docMouseDownHandlerRef.current) {
      document.removeEventListener('mousedown', docMouseDownHandlerRef.current, true)
      docMouseDownHandlerRef.current = null
    }
  }

  function bindClickOutside() {
    unbindClickOutside()
    docMouseDownHandlerRef.current = (e: MouseEvent) => {
      const root = rootRef.current
      const panel = panelRef.current
      if (!openRef.current || !root) return
      const target = e.target as Node | null
      if (!target) return
      if (root.contains(target) || (panel && panel.contains(target))) return
      setOpenBoth(false)
    }
    document.addEventListener('mousedown', docMouseDownHandlerRef.current, true)
  }

  // 原 deep watch prefetchedModels：父级传入数组，以引用变化为准
  useEffect(() => {
    if (openRef.current) void loadOptions()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prefetchedModels])

  // 原 watch(() => open.value, ..., { flush: 'post' })
  useEffect(() => {
    if (open) {
      setReadyToShowPanel(false)
      unbindClickOutside()
      void loadOptions()
      let cancelled = false
      // 原 await nextTick()：等触发区渲染稳定后再计算方向
      requestAnimationFrame(() => {
        if (cancelled) return
        updatePlacement()
        setReadyToShowPanel(true)
        // 原第二个 await nextTick()：面板挂载后再绑定 click-outside
        requestAnimationFrame(() => {
          if (cancelled) return
          bindClickOutside()
        })
      })
      return () => {
        cancelled = true
      }
    }
    setReadyToShowPanel(false)
    unbindClickOutside()
    return undefined
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // 原 watch(() => props.imageIndex)：展开时索引变化需重算定位
  useEffect(() => {
    if (openRef.current) updatePlacement()
     
  }, [imageIndex])

  // 复刻 <Transition name="upscale-model-fade">：进入/离开动画 class + 离场后再卸载
  const visible = open && readyToShowPanel
  useEffect(() => {
    if (transitionTimerRef.current) {
      clearTimeout(transitionTimerRef.current)
      transitionTimerRef.current = null
    }

    if (visible) {
      renderedRef.current = true
      setRendered(true)
      setTransitionClass('upscale-model-fade-enter-from upscale-model-fade-enter-active')
      nextFrame(() => {
        setTransitionClass('upscale-model-fade-enter-active')
        transitionTimerRef.current = setTimeout(() => {
          transitionTimerRef.current = null
          setTransitionClass('')
        }, FADE_DURATION_MS)
      })
      return
    }

    if (!renderedRef.current) return
    setTransitionClass('upscale-model-fade-leave-active upscale-model-fade-leave-to')
    transitionTimerRef.current = setTimeout(() => {
      transitionTimerRef.current = null
      renderedRef.current = false
      setRendered(false)
      setTransitionClass('')
      // 离场结束后再复位方向与定位（Vue 在关闭瞬间清空，React 侧保留至卸载避免离场闪跳）
      setOpenUpward(false)
      setPanelFixedStyle({})
    }, FADE_DURATION_MS)
  }, [visible])

  useEffect(() => {
    const onViewportChange = () => {
      if (openRef.current) updatePlacement()
    }
    window.addEventListener('resize', onViewportChange)
    window.addEventListener('scroll', onViewportChange, true)
    return () => {
      unbindClickOutside()
      window.removeEventListener('resize', onViewportChange)
      window.removeEventListener('scroll', onViewportChange, true)
      if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current)
    }
     
  }, [])

  const panelClass = [
    'upscale-model-panel',
    !openUpward ? 'is-open-down' : 'is-open-up',
    transitionClass
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div ref={rootRef} className="upscale-model-popover-root">
      <div
        ref={triggerRef}
        className={
          disabled
            ? 'upscale-model-popover-trigger is-disabled'
            : 'upscale-model-popover-trigger'
        }
        onClick={(e) => {
          e.stopPropagation()
          toggle()
        }}
      >
        {children}
      </div>

      {rendered && typeof document !== 'undefined'
        ? createPortal(
            <div
              ref={panelRef}
              className={panelClass}
              style={panelStyle}
              role="menu"
              aria-label="变清晰模型"
            >
              {loading ? (
                <div className="upscale-model-empty">加载中…</div>
              ) : modelOptions.length ? (
                <div className="upscale-model-list">
                  {modelOptions.map((opt) => (
                    <button
                      key={`upscale-${opt.id}`}
                      type="button"
                      className="upscale-model-item"
                      role="menuitem"
                      disabled={generating}
                      onClick={(e) => {
                        e.stopPropagation()
                        pick(opt)
                      }}
                    >
                      <div className="upscale-model-thumb" aria-hidden="true">
                        {opt.icon ? (
                          <img src={opt.icon} alt={opt.name} className="upscale-model-thumb__img" />
                        ) : (
                          <span className="upscale-model-thumb__letter">
                            {(opt.name || '?').slice(0, 1)}
                          </span>
                        )}
                      </div>
                      <div className="upscale-model-body">
                        <div className="upscale-model-title-row">
                          <span className="upscale-model-title">{opt.name}</span>
                          {shouldShowModelFreeBadge(opt) ? <ModelFreeBadge /> : null}
                          {opt.resolutionLabel ? (
                            <span className="upscale-model-tag">{opt.resolutionLabel}</span>
                          ) : null}
                        </div>
                        {opt.desc ? <p className="upscale-model-desc">{opt.desc}</p> : null}
                      </div>
                    </button>
                  ))}
                </div>
              ) : (
                <div className="upscale-model-empty">暂无可用高清模型</div>
              )}
            </div>,
            document.body
          )
        : null}
    </div>
  )
}

export default UpscaleModelPopover
