// app/create/scene-character/page.tsx
'use client'

/** 原 pages/create/scene-character.vue（definePageMeta layout:'create'）：素材准备步骤薄页面 */

import { Suspense } from 'react'
import { SceneCharacterProp } from '~/components/steps/SceneCharacterProp'
import { useCreateFlowShell } from '~/composables/useCreateFlowShell'
import { useCreationStore } from '~/stores/creation'

function SceneCharacterStepClient() {
  const sceneCharacter = useCreationStore((s) => s.formData.sceneCharacter)
  const storyScriptContent = useCreationStore((s) => s.formData.storyScript.content)
  const isExtractingAssets = useCreationStore((s) => s.isExtractingAssets)
  const extractingStage = useCreationStore((s) => s.extractingStage)
  const extractingStages = useCreationStore((s) => s.extractingStages)
  const shell = useCreateFlowShell()

  return (
    <SceneCharacterProp
      modelValue={sceneCharacter}
      storyScriptContent={storyScriptContent}
      isExtracting={isExtractingAssets}
      extractingStage={extractingStage}
      extractingStages={extractingStages}
      onModelValueChange={(v) => useCreationStore.getState().updateSceneCharacterData(v)}
      onStopExtract={() => void shell.stopExtractAssets()}
      onOpenExtractModal={shell.openExtractModalFromScp}
    />
  )
}

export default function SceneCharacterStepPage() {
  return (
    <Suspense fallback={null}>
      <SceneCharacterStepClient />
    </Suspense>
  )
}

// pages/create/scene-character.vue
<template>
  <SceneCharacterProp
    :model-value="formData.sceneCharacter"
    :story-script-content="formData.storyScript.content"
    :is-extracting="creationStore.isExtractingAssets"
    :extracting-stage="extractingStage"
    :extracting-stages="extractingStages"
    @update:model-value="creationStore.updateSceneCharacterData"
    @stop-extract="shell.stopExtractAssets"
    @open-extract-modal="shell.openExtractModalFromScp"
  />
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import SceneCharacterProp from '~/components/steps/SceneCharacterProp.vue'
import { useCreationStore } from '~/stores/creation'
import { useCreateFlowShell } from '~/composables/useCreateFlowShell'

definePageMeta({ layout: 'create' })

const creationStore = useCreationStore()
const { formData, extractingStage, extractingStages } = storeToRefs(creationStore)
const shell = useCreateFlowShell()
</script>
