// app/create/story-script/page.tsx
'use client'

/** 原 pages/create/story-script.vue（definePageMeta layout:'create'）：剧本创作步骤薄页面 */

import { Suspense } from 'react'
import { StoryScript } from '~/components/steps/StoryScript'
import { useCreationStore } from '~/stores/creation'

function StoryScriptStepClient() {
  const content = useCreationStore((s) => s.formData.storyScript.content)

  function onUpdate(v: string) {
    useCreationStore.getState().updateFormData({ storyScript: { content: v } })
  }

  return <StoryScript value={content} onChange={onUpdate} />
}

export default function StoryScriptStepPage() {
  return (
    <Suspense fallback={null}>
      <StoryScriptStepClient />
    </Suspense>
  )
}

// pages/create/story-script.vue
<template>
  <StoryScript
    :model-value="formData.storyScript.content"
    @update:model-value="onUpdate"
  />
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import StoryScript from '~/components/steps/StoryScript.vue'
import { useCreationStore } from '~/stores/creation'

definePageMeta({ layout: 'create' })

const creationStore = useCreationStore()
const { formData } = storeToRefs(creationStore)

function onUpdate(v: string) {
  creationStore.updateFormData({ storyScript: { content: v } })
}
</script>
