// components/common/AsyncModalLoading.vue
<template>
  <div class="async-modal-loading" role="dialog" aria-modal="true" aria-label="正在打开编辑器">
    <div class="async-modal-loading__backdrop" />
    <div class="async-modal-loading__panel" aria-live="polite" aria-busy="true">
      <LoadingOutlined spin class="async-modal-loading__icon" />
      <span>正在打开编辑器...</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { LoadingOutlined } from '@ant-design/icons-vue'
</script>

<style scoped>
.async-modal-loading {
  position: fixed;
  inset: 0;
  z-index: 1100;
  display: grid;
  place-items: center;
}

.async-modal-loading__backdrop {
  position: absolute;
  inset: 0;
  background: rgb(0 0 0 / 45%);
}

.async-modal-loading__panel {
  position: relative;
  display: flex;
  min-width: 184px;
  min-height: 88px;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 20px 24px;
  border-radius: 8px;
  background: #fff;
  box-shadow: 0 12px 36px rgb(0 0 0 / 18%);
  color: #262626;
  font-size: 14px;
}

.async-modal-loading__icon {
  color: #1677ff;
  font-size: 20px;
}
</style>

// components/common/AsyncModalLoading.tsx
'use client'

import { LoadingOutlined } from '@ant-design/icons'

/** 异步弹窗 chunk 加载期间的全屏 loading 遮罩 */
export function AsyncModalLoading() {
  return (
    <div
      className="async-modal-loading fixed inset-0 z-[1100] grid place-items-center"
      role="dialog"
      aria-modal="true"
      aria-label="正在打开编辑器"
    >
      <div className="async-modal-loading__backdrop absolute inset-0 bg-[rgb(0_0_0/45%)]" />
      <div
        className="async-modal-loading__panel relative flex min-w-[184px] min-h-[88px] items-center justify-center gap-[10px] px-[24px] py-[20px] rounded-[8px] border border-solid border-[rgba(74,231,253,0.28)] bg-[#191a1d] shadow-[0_12px_36px_rgb(0_0_0/45%)] text-[#e6edf3] text-[14px]"
        aria-live="polite"
        aria-busy="true"
      >
        <LoadingOutlined spin className="async-modal-loading__icon text-[#00abd8] text-[20px]" />
        <span>正在打开编辑器...</span>
      </div>
    </div>
  )
}
