// components/common/EllipsisTooltip.vue
<template>
  <a-tooltip :title="showTooltip ? title : undefined" :placement="placement">
    <span ref="textRef" class="ellipsis-tooltip-text">
      <slot>{{ title }}</slot>
    </span>
  </a-tooltip>
</template>

<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    title: string
    placement?: 'top' | 'bottom' | 'left' | 'right'
  }>(),
  { placement: 'top' }
)

const textRef = ref<HTMLElement | null>(null)
const showTooltip = ref(false)

function checkOverflow() {
  const el = textRef.value
  if (!el) {
    showTooltip.value = false
    return
  }
  showTooltip.value = el.scrollWidth > el.clientWidth + 1
}

let resizeObserver: ResizeObserver | null = null

onMounted(() => {
  checkOverflow()
  if (typeof ResizeObserver === 'undefined' || !textRef.value) return
  resizeObserver = new ResizeObserver(checkOverflow)
  resizeObserver.observe(textRef.value)
})

onBeforeUnmount(() => {
  resizeObserver?.disconnect()
  resizeObserver = null
})

watch(
  () => props.title,
  () => nextTick(checkOverflow)
)
</script>

<style scoped>
.ellipsis-tooltip-text {
  display: inline-block;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  vertical-align: bottom;
}
</style>

// components/common/EllipsisTooltip.tsx
'use client'

import { Tooltip } from 'antd'
import type { ReactNode } from 'react'
import { useEffect,useRef,useState } from 'react'

export interface EllipsisTooltipProps {
  title: string
  placement?: 'top' | 'bottom' | 'left' | 'right'
  children?: ReactNode
}

/** 文本溢出（省略号）时才显示 Tooltip */
export function EllipsisTooltip({ title, placement = 'top', children }: EllipsisTooltipProps) {
  const textRef = useRef<HTMLSpanElement | null>(null)
  const [showTooltip, setShowTooltip] = useState(false)

  function checkOverflow() {
    const el = textRef.current
    if (!el) {
      setShowTooltip(false)
      return
    }
    setShowTooltip(el.scrollWidth > el.clientWidth + 1)
  }

  useEffect(() => {
    checkOverflow()
    if (typeof ResizeObserver === 'undefined' || !textRef.current) return
    const resizeObserver = new ResizeObserver(checkOverflow)
    resizeObserver.observe(textRef.current)
    return () => resizeObserver.disconnect()
     
  }, [])

  useEffect(() => {
    const raf = requestAnimationFrame(checkOverflow)
    return () => cancelAnimationFrame(raf)
     
  }, [title])

  return (
    <Tooltip title={showTooltip ? title : undefined} placement={placement}>
      <span
        ref={textRef}
        className="ellipsis-tooltip-text inline-block max-w-full overflow-hidden text-ellipsis whitespace-nowrap align-bottom"
      >
        {children ?? title}
      </span>
    </Tooltip>
  )
}
