// components/common/HorizontalScrollTabBar.vue
<template>
  <div :class="['h-scroll-tab-bar', rootClass]">
    <button
      v-show="showLeftArrow"
      type="button"
      class="h-scroll-tab-bar__arrow h-scroll-tab-bar__arrow--left"
      aria-label="向左滚动"
      @click="scrollByPage(-1)"
    >
      <LeftOutlined />
    </button>

    <div
      ref="scrollerRef"
      class="h-scroll-tab-bar__viewport"
      @scroll="onScroll"
    >
      <div :class="['h-scroll-tab-bar__track', trackClass]">
        <slot />
      </div>
    </div>

    <button
      v-show="showRightArrow"
      type="button"
      class="h-scroll-tab-bar__arrow h-scroll-tab-bar__arrow--right"
      aria-label="向右滚动"
      @click="scrollByPage(1)"
    >
      <RightOutlined />
    </button>

    <div v-if="$slots.suffix" class="h-scroll-tab-bar__suffix">
      <slot name="suffix" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { LeftOutlined, RightOutlined } from '@ant-design/icons-vue'
import { useHorizontalScrollTabs } from '~/composables/useHorizontalScrollTabs'

withDefaults(
  defineProps<{
    rootClass?: string
    trackClass?: string
  }>(),
  {
    rootClass: '',
    trackClass: ''
  }
)

const {
  scrollerRef,
  showLeftArrow,
  showRightArrow,
  onScroll,
  scrollByPage,
  scrollItemIntoView,
  refresh,
  updateArrows
} = useHorizontalScrollTabs()

defineExpose({
  scrollItemIntoView,
  refresh,
  updateArrows
})
</script>

<style lang="scss" scoped>
.h-scroll-tab-bar {
  display: flex;
  align-items: center;
  flex: 1;
  min-width: 0;
  gap: 4px;
}

.h-scroll-tab-bar__viewport {
  flex: 1;
  min-width: 0;
  overflow-x: auto;
  overflow-y: hidden;
  scroll-behavior: smooth;
  scrollbar-width: none;

  &::-webkit-scrollbar {
    display: none;
  }
}

.h-scroll-tab-bar__track {
  display: inline-flex;
  flex-wrap: nowrap;
  align-items: stretch;
  width: max-content;
  flex-shrink: 0;
}

.h-scroll-tab-bar__track :deep(> *) {
  flex-shrink: 0;
}

.h-scroll-tab-bar__arrow {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  padding: 0;
  border: none;
  border-radius: 6px;
  color: #d9e6f2;
  background: rgba(74, 231, 253, 0.12);
  cursor: pointer;
  transition:
    color 0.2s ease,
    background 0.2s ease;

  &:hover {
    color: #4ae7fd;
    background: rgba(74, 231, 253, 0.22);
  }
}

.h-scroll-tab-bar__suffix {
  flex-shrink: 0;
  margin-left: 8px;
}
</style>

// components/common/HorizontalScrollTabBar.tsx
'use client'

import { useHorizontalScrollTabs } from '@/hooks/useHorizontalScrollTabs'
import { LeftOutlined,RightOutlined } from '@ant-design/icons'
import { forwardRef,useImperativeHandle,type ReactNode } from 'react'
import './HorizontalScrollTabBar.css'

export interface HorizontalScrollTabBarProps {
  rootClass?: string
  trackClass?: string
  children?: ReactNode
  /** 原 suffix 插槽：右侧固定区（如「更多」按钮） */
  suffix?: ReactNode
}

export interface HorizontalScrollTabBarHandle {
  scrollItemIntoView: (selector: string, behavior?: ScrollBehavior, padding?: number) => void
  refresh: () => void
  updateArrows: () => void
}

/** 横向滚动 tab 条：溢出时两侧出翻页箭头 */
export const HorizontalScrollTabBar = forwardRef<
  HorizontalScrollTabBarHandle,
  HorizontalScrollTabBarProps
>(function HorizontalScrollTabBar({ rootClass = '', trackClass = '', children, suffix }, ref) {
  const {
    scrollerRef,
    showLeftArrow,
    showRightArrow,
    onScroll,
    scrollByPage,
    scrollItemIntoView,
    refresh,
    updateArrows
  } = useHorizontalScrollTabs()

  useImperativeHandle(ref, () => ({ scrollItemIntoView, refresh, updateArrows }), [
    scrollItemIntoView,
    refresh,
    updateArrows
  ])

  return (
    <div className={`h-scroll-tab-bar${rootClass ? ` ${rootClass}` : ''}`}>
      <button
        type="button"
        className="h-scroll-tab-bar__arrow h-scroll-tab-bar__arrow--left"
        aria-label="向左滚动"
        style={showLeftArrow ? undefined : { display: 'none' }}
        onClick={() => scrollByPage(-1)}
      >
        <LeftOutlined />
      </button>

      <div
        ref={scrollerRef as React.RefObject<HTMLDivElement>}
        className="h-scroll-tab-bar__viewport"
        onScroll={onScroll}
      >
        <div className={`h-scroll-tab-bar__track${trackClass ? ` ${trackClass}` : ''}`}>
          {children}
        </div>
      </div>

      <button
        type="button"
        className="h-scroll-tab-bar__arrow h-scroll-tab-bar__arrow--right"
        aria-label="向右滚动"
        style={showRightArrow ? undefined : { display: 'none' }}
        onClick={() => scrollByPage(1)}
      >
        <RightOutlined />
      </button>

      {suffix ? <div className="h-scroll-tab-bar__suffix">{suffix}</div> : null}
    </div>
  )
})

export default HorizontalScrollTabBar
